<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.multiQuote
* generated at Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.multiQuote.button.quote'] = 'Zitieren';
$this->items[$this->languageID]['wcf.multiQuote.button.quoteMultiple'] = '"Zitieren" + (objectValue.quotes > 0 ? " ("+objectValue.quotes+")" : "")';
$this->items[$this->languageID]['wcf.multiQuote.quote.insertQuote'] = 'Zitat in Text einfügen';
$this->items[$this->languageID]['wcf.multiQuote.quote.markParagraphToQuote'] = 'Absatz zum Zitieren auswählen';
$this->items[$this->languageID]['wcf.multiQuote.quote.markParagraphsToQuote'] = 'Absätze zum Zitieren auswählen';
$this->items[$this->languageID]['wcf.multiQuote.quote.markTextToQuote'] = 'Textstelle zum Zitieren auswählen';
$this->items[$this->languageID]['wcf.multiQuote.quote.markToQuote'] = 'Nachricht zum Zitieren auswählen';
$this->items[$this->languageID]['wcf.multiQuote.quote.noQuotes'] = 'Sie haben keine Zitate gespeichert.';
$this->items[$this->languageID]['wcf.multiQuote.quote.quoteDirectly'] = 'Nachricht direkt zitieren';
$this->items[$this->languageID]['wcf.multiQuote.quote.quoteParagraphDirectly'] = 'Absatz direkt zitieren';
$this->items[$this->languageID]['wcf.multiQuote.quote.quoteParagraphsDirectly'] = 'Absätze direkt zitieren';
$this->items[$this->languageID]['wcf.multiQuote.quote.quoteTextDirectly'] = 'Textstelle direkt zitieren';
$this->items[$this->languageID]['wcf.multiQuote.quote.removeQuote'] = 'Zitat entfernen';
$this->items[$this->languageID]['wcf.multiQuote.quote.removeQuotes'] = 'Ausgewählte Zitate entfernen';
$this->items[$this->languageID]['wcf.multiQuote.quote.selectedQuotes'] = '(count > 1 ? "Die ausgewählten Zitate werden" : "Das ausgewählte Zitat wird") + " nach dem Absenden des Formulars gelöscht."';
$this->items[$this->languageID]['wcf.multiQuote.title'] = 'Zitate';
?>