<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.header.menu
* generated at Wed, 28 May 2014 19:04:12 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.header.menu.help'] = 'Hilfe';
$this->items[$this->languageID]['wcf.header.menu.memberslist'] = 'Mitglieder';
?>