<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.page
* generated at Wed, 28 May 2014 19:46:43 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.page.pageNo'] = 'Seite {#$pageNo}';
$this->dynamicItems[$this->languageID]['wcf.page.pageNo'] = 'Seite <?php echo StringUtil::formatNumeric($this->v[\'pageNo\']); ?>';
?>