<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wbb.acp.menu
* generated at Wed, 28 May 2014 19:04:09 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.acp.menu.link.content.board'] = 'Forenverwaltung';
$this->items[$this->languageID]['wbb.acp.menu.link.content.board.add'] = 'Forum hinzufügen';
$this->items[$this->languageID]['wbb.acp.menu.link.content.board.view'] = 'Foren auflisten';
$this->items[$this->languageID]['wbb.acp.menu.link.content.threadsAndPosts'] = 'Themen &amp; Beiträge';
$this->items[$this->languageID]['wbb.acp.menu.link.content.threadsAndPosts.massProcessing'] = 'Massenverarbeitung von Themen';
$this->items[$this->languageID]['wbb.acp.menu.link.content.threadsAndPosts.postsMassProcessing'] = 'Massenverarbeitung von Beiträgen';
$this->items[$this->languageID]['wbb.acp.menu.link.maintenance.updateCounters'] = 'Anzeigen aktualisieren';
?>