<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.smiley
* generated at Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.smiley.category.default'] = 'Standard';
$this->items[$this->languageID]['wcf.smiley.smilies'] = 'Smileys';
?>