<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.message.sidebar
* generated at Wed, 28 May 2014 19:47:36 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.message.sidebar.skip'] = 'Benutzerinformationen überspringen';
?>