<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.user.team
* generated at Sun, 08 Jun 2014 20:06:52 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.team.error.noMembers'] = 'Es sind keine Team-Mitglieder eingetragen.';
$this->items[$this->languageID]['wcf.user.team.leaders'] = 'Leiter';
$this->items[$this->languageID]['wcf.user.team.members'] = 'Mitglieder';
$this->items[$this->languageID]['wcf.user.team.title'] = 'Team-Mitglieder';
?>