<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wbb.acp
* generated at Wed, 28 May 2014 19:04:09 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.acp.jumpToBoard'] = 'Zum Forum';
?>