<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.user.lostPassword
* generated at Sun, 08 Jun 2014 22:05:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.lostPassword.description'] = 'Wenn Sie Ihr Kennwort vergessen haben, müssen Sie entweder den Benutzernamen oder die E-Mail-Adresse angeben, die Sie in Ihrem Profil hinterlegt haben. Sie können dabei nur eines der beiden Felder ausfüllen. Wenn Sie beide Daten nicht mehr wissen, wenden Sie sich bitte an den Administrator.';
$this->items[$this->languageID]['wcf.user.lostPassword.error.email.notFound'] = 'Es wurde kein Benutzer mit der E-Mail-Adresse: &raquo;{$email}&laquo; gefunden.';
$this->dynamicItems[$this->languageID]['wcf.user.lostPassword.error.email.notFound'] = 'Es wurde kein Benutzer mit der E-Mail-Adresse: &raquo;<?php echo StringUtil::encodeHTML($this->v[\'email\']); ?>&laquo; gefunden.';
$this->items[$this->languageID]['wcf.user.lostPassword.error.lostPasswordKey.invalid'] = 'Sie haben einen ungültigen Sicherheitsschlüssel angegeben.';
$this->items[$this->languageID]['wcf.user.lostPassword.error.tooManyRequests'] = 'Das Kennwort für dieses Benutzerkonto wurde in den letzten 24 Stunden bereits einmal angefordert. Aus Sicherheitsgründen kann das Kennwort eines Benutzers nur einmal pro Tag angefordert werden. Sie können das Kennwort für dieses Benutzerkonto in {$hours} Stunde(n) erneut anfordern.';
$this->dynamicItems[$this->languageID]['wcf.user.lostPassword.error.tooManyRequests'] = 'Das Kennwort für dieses Benutzerkonto wurde in den letzten 24 Stunden bereits einmal angefordert. Aus Sicherheitsgründen kann das Kennwort eines Benutzers nur einmal pro Tag angefordert werden. Sie können das Kennwort für dieses Benutzerkonto in <?php echo StringUtil::encodeHTML($this->v[\'hours\']); ?> Stunde(n) erneut anfordern.';
$this->items[$this->languageID]['wcf.user.lostPassword.error.userID.invalid'] = 'Sie haben eine ungültige Benutzer-ID angegeben.';
$this->items[$this->languageID]['wcf.user.lostPassword.lostPasswordKey'] = 'Sicherheitsschlüssel';
$this->items[$this->languageID]['wcf.user.lostPassword.mail'] = 'Hallo {$username},

wenn Sie Ihr Kennwort vergessen haben, können Sie über folgenden Link ein neues Kennwort anfordern.
Klicken Sie hier, um ein neues Kennwort anzufordern: {PAGE_URL}/index.php?form=NewPassword&action=new&u={$userID}&k={$key}

Falls Sie Ihr Kennwort nicht vergessen haben, können Sie diese E-Mail ignorieren.


Vielen Dank,
Ihr {PAGE_TITLE} Team';
$this->dynamicItems[$this->languageID]['wcf.user.lostPassword.mail'] = 'Hallo <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>,

wenn Sie Ihr Kennwort vergessen haben, können Sie über folgenden Link ein neues Kennwort anfordern.
Klicken Sie hier, um ein neues Kennwort anzufordern: <?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?form=NewPassword&action=new&u=<?php echo StringUtil::encodeHTML($this->v[\'userID\']); ?>&k=<?php echo StringUtil::encodeHTML($this->v[\'key\']); ?>

Falls Sie Ihr Kennwort nicht vergessen haben, können Sie diese E-Mail ignorieren.


Vielen Dank,
Ihr <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> Team';
$this->items[$this->languageID]['wcf.user.lostPassword.mail.sent'] = 'Sie erhalten in Kürze eine E-Mail mit weiteren Informationen.';
$this->items[$this->languageID]['wcf.user.lostPassword.mail.subject'] = 'Kennwort vergessen auf der Website: {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.user.lostPassword.mail.subject'] = 'Kennwort vergessen auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.user.lostPassword.newPassword.mail'] = 'Hallo {$username},

Ihr neues Kennwort für die Website "{PAGE_TITLE}" lautet:
{$newPassword}

Sie können Ihr Kennwort unter folgender Adresse jederzeit ändern: 
{PAGE_URL}/index.php?form=AccountManagement


Vielen Dank,
Ihr {PAGE_TITLE} Team';
$this->dynamicItems[$this->languageID]['wcf.user.lostPassword.newPassword.mail'] = 'Hallo <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>,

Ihr neues Kennwort für die Website "<?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>" lautet:
<?php echo StringUtil::encodeHTML($this->v[\'newPassword\']); ?>

Sie können Ihr Kennwort unter folgender Adresse jederzeit ändern: 
<?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?form=AccountManagement


Vielen Dank,
Ihr <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> Team';
$this->items[$this->languageID]['wcf.user.lostPassword.newPassword.mail.subject'] = 'Neues Kennwort auf der Website: {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.user.lostPassword.newPassword.mail.subject'] = 'Neues Kennwort auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.user.lostPassword.newPassword.title'] = 'Neues Kennwort anfordern';
$this->items[$this->languageID]['wcf.user.lostPassword.success'] = 'Sie erhalten in Kürze eine E-Mail mit Ihrem neuen Kennwort.';
$this->items[$this->languageID]['wcf.user.lostPassword.title'] = 'Kennwort vergessen';
?>