<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.user.signature
* generated at Sun, 08 Jun 2014 21:37:21 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.signature'] = 'Signatur';
$this->items[$this->languageID]['wcf.user.signature.current'] = 'Bisherige Signatur';
$this->items[$this->languageID]['wcf.user.signature.error.disabled'] = '{if $this->user->disableSignatureReason}Ihre Signatur wurde vom Administrator aus folgenden Gründen gesperrt: {$this->user->disableSignatureReason}{else}Ihre Signatur wurde vom Administrator gesperrt.{/if}';
$this->dynamicItems[$this->languageID]['wcf.user.signature.error.disabled'] = '<?php if ($this->v[\'this\']->user->disableSignatureReason) { ?>Ihre Signatur wurde vom Administrator aus folgenden Gründen gesperrt: <?php echo StringUtil::encodeHTML($this->v[\'this\']->user->disableSignatureReason); ?><?php } else { ?>Ihre Signatur wurde vom Administrator gesperrt.<?php } ?>';
$this->items[$this->languageID]['wcf.user.signature.error.imageTooLarge'] = 'Das Bild &raquo;{$error.image}&laquo; überschreitet die erlaubte Maximalgröße. Die maximale Größe liegt bei {#$this->user->getPermission(\'user.profile.signature.maxImageWidth\')}*{#$this->user->getPermission(\'user.profile.signature.maxImageHeight\')} Pixel und {@$this->user->getPermission(\'user.profile.signature.maxImageSize\')|filesize}.';
$this->dynamicItems[$this->languageID]['wcf.user.signature.error.imageTooLarge'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierFilesize\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierFilesize.class.php\');
$this->pluginObjects[\'TemplatePluginModifierFilesize\'] = new TemplatePluginModifierFilesize;
}
?>Das Bild &raquo;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'image\']); ?>&laquo; überschreitet die erlaubte Maximalgröße. Die maximale Größe liegt bei <?php echo StringUtil::formatNumeric($this->v[\'this\']->user->getPermission(\'user.profile.signature.maxImageWidth\')); ?>*<?php echo StringUtil::formatNumeric($this->v[\'this\']->user->getPermission(\'user.profile.signature.maxImageHeight\')); ?> Pixel und <?php echo $this->pluginObjects[\'TemplatePluginModifierFilesize\']->execute(array($this->v[\'this\']->user->getPermission(\'user.profile.signature.maxImageSize\')), $this); ?>.';
$this->items[$this->languageID]['wcf.user.signature.error.tooLong'] = 'Ihre Signatur ist zu lang. Es stehen maximal {#$maxTextLength} Zeichen zur Verfügung.';
$this->dynamicItems[$this->languageID]['wcf.user.signature.error.tooLong'] = 'Ihre Signatur ist zu lang. Es stehen maximal <?php echo StringUtil::formatNumeric($this->v[\'maxTextLength\']); ?> Zeichen zur Verfügung.';
$this->items[$this->languageID]['wcf.user.signature.error.tooManyImages'] = 'Ihre Signatur enthält zu viele Bilder. Es {if $maxImages == 1}ist{else}sind{/if} maximal nur {#$maxImages} Bild{if $maxImages != 1}er{/if} pro Signatur erlaubt.';
$this->dynamicItems[$this->languageID]['wcf.user.signature.error.tooManyImages'] = 'Ihre Signatur enthält zu viele Bilder. Es <?php if ($this->v[\'maxImages\'] == 1) { ?>ist<?php } else { ?>sind<?php } ?> maximal nur <?php echo StringUtil::formatNumeric($this->v[\'maxImages\']); ?> Bild<?php if ($this->v[\'maxImages\'] != 1) { ?>er<?php } ?> pro Signatur erlaubt.';
$this->items[$this->languageID]['wcf.user.signature.preview'] = 'Neue Signatur';
$this->items[$this->languageID]['wcf.user.signature.success'] = 'Ihre Signatur wurde erfolgreich gespeichert.';
$this->items[$this->languageID]['wcf.user.signature.title'] = 'Signatur bearbeiten';
?>