<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wbb.acp.user
* generated at Wed, 28 May 2014 19:44:07 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.acp.user.button.merge'] = 'Zusammenführen';
$this->items[$this->languageID]['wbb.acp.user.merge'] = 'Benutzer zusammenführen';
$this->items[$this->languageID]['wbb.acp.user.merge.error.tooFew'] = 'Sie müssen mindestens 2 Benutzer für eine Zusammenführung auswählen.';
$this->items[$this->languageID]['wbb.acp.user.merge.markedUsers'] = 'Folgende Benutzer zusammenführen';
$this->items[$this->languageID]['wbb.acp.user.merge.primaryUser'] = 'Ziel';
$this->items[$this->languageID]['wbb.acp.user.merge.primaryUser.description'] = 'Ausgewählte Benutzer in diesem Benutzer-Account zusammenführen.';
$this->items[$this->languageID]['wbb.acp.user.merge.success'] = 'Die Benutzer wurden erfolgreich zusammengeführt.';
$this->items[$this->languageID]['wbb.acp.user.search.conditions'] = 'Bedingungen';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.date.after'] = 'Nach dem';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.date.before'] = 'Vor dem';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.greaterThan'] = 'Größer als';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.lessThan'] = 'Kleiner als';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.status'] = 'Zustände';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.status.banned'] = 'Gesperrt';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.status.enabled'] = 'Aktiviert';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.status.hasSpecialPermissions'] = 'Besitzt spezielle Zugriffsrechte für Foren';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.status.notBanned'] = 'Nicht gesperrt';
$this->items[$this->languageID]['wbb.acp.user.search.conditions.status.notEnabled'] = 'Nicht aktiviert';
?>