<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.captcha
* generated at Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.captcha.captchaString'] = 'Sicherheitsmaßnahme';
$this->items[$this->languageID]['wcf.captcha.captchaString.description'] = 'Bitte geben Sie die untenstehenden Zeichen ohne Leerstellen in das leere Feld ein. Groß- und Kleinschreibung müssen nicht beachtet werden. Sollten Sie das Bild auch nach mehrfachem Neuladen nicht entziffern können, wenden Sie sich an den Administrator dieser Seite.';
$this->items[$this->languageID]['wcf.captcha.captchaString.title'] = 'Sicherheitscode';
$this->items[$this->languageID]['wcf.captcha.error.captchaString.false'] = 'Sie haben leider nicht die korrekten Zeichen eingegeben. Bitte versuchen Sie es erneut!';
$this->items[$this->languageID]['wcf.captcha.maximize'] = 'Bild vergrößern';
$this->items[$this->languageID]['wcf.captcha.minimize'] = 'Bild verkleinern';
$this->items[$this->languageID]['wcf.captcha.reload'] = 'Neues Captchabild laden';
?>