<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.message
* generated at Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.message.addToPost'] = 'In den Beitrag einfügen';
$this->items[$this->languageID]['wcf.message.error.censoredWordsFound'] = 'Ihre Nachricht enthält folgende zensierte Wörter: {implode from=$censoredWords key=censoredWord item=number}{$censoredWord}{if $number > 1} ({#$number}x){/if}{/implode}';
$this->dynamicItems[$this->languageID]['wcf.message.error.censoredWordsFound'] = 'Ihre Nachricht enthält folgende zensierte Wörter: <?php
$_lengthbc47f006135879b536846fd2ce332ee7c3f5da25 = count($this->v[\'censoredWords\']);
$_ibc47f006135879b536846fd2ce332ee7c3f5da25 = 0;
foreach ($this->v[\'censoredWords\'] as $this->v[\'censoredWord\'] => $this->v[\'number\']) { ?><?php echo StringUtil::encodeHTML($this->v[\'censoredWord\']); ?><?php if ($this->v[\'number\'] > 1) { ?> (<?php echo StringUtil::formatNumeric($this->v[\'number\']); ?>x)<?php } ?><?php
if (++$_ibc47f006135879b536846fd2ce332ee7c3f5da25 < $_lengthbc47f006135879b536846fd2ce332ee7c3f5da25) { echo \', \'; }
} ?>';
$this->items[$this->languageID]['wcf.message.error.floodControl'] = 'Sie haben bereits eine Nachricht innerhalb der letzten {$floodControlTime} Sekunden erstellt. Sie können erst in {$waitingTime} Sekunden eine neue Nachricht erstellen.';
$this->dynamicItems[$this->languageID]['wcf.message.error.floodControl'] = 'Sie haben bereits eine Nachricht innerhalb der letzten <?php echo StringUtil::encodeHTML($this->v[\'floodControlTime\']); ?> Sekunden erstellt. Sie können erst in <?php echo StringUtil::encodeHTML($this->v[\'waitingTime\']); ?> Sekunden eine neue Nachricht erstellen.';
$this->items[$this->languageID]['wcf.message.error.tooLong'] = 'Ihre Nachricht ist zu lang. Es stehen maximal {#$maxTextLength} Zeichen zur Verfügung.';
$this->dynamicItems[$this->languageID]['wcf.message.error.tooLong'] = 'Ihre Nachricht ist zu lang. Es stehen maximal <?php echo StringUtil::formatNumeric($this->v[\'maxTextLength\']); ?> Zeichen zur Verfügung.';
$this->items[$this->languageID]['wcf.message.preview'] = 'Vorschau der neuen Nachricht';
$this->items[$this->languageID]['wcf.message.settings'] = 'Einstellungen';
$this->items[$this->languageID]['wcf.message.settings.enableBBCodes'] = 'Darstellung von BBCodes aktivieren';
$this->items[$this->languageID]['wcf.message.settings.enableBBCodes.description'] = 'Sie können BBCodes zur Formatierung nutzen, sofern diese Option aktiviert ist.';
$this->items[$this->languageID]['wcf.message.settings.enableHtml'] = 'Darstellung von HTML aktivieren';
$this->items[$this->languageID]['wcf.message.settings.enableHtml.description'] = 'Wenn Sie diese Option aktiviert haben, können Sie HTML zur Formatierung verwenden.';
$this->items[$this->languageID]['wcf.message.settings.enableSmilies'] = 'Darstellung von Smileys aktivieren';
$this->items[$this->languageID]['wcf.message.settings.enableSmilies.description'] = 'Smiley-Code wird in Ihrem Beitrag automatisch als Smiley-Grafik dargestellt.';
$this->items[$this->languageID]['wcf.message.settings.parseURL'] = 'URLs automatisch erkennen';
$this->items[$this->languageID]['wcf.message.settings.parseURL.description'] = 'Internet-Adressen werden automatisch erkannt und umgewandelt.';
$this->items[$this->languageID]['wcf.message.settings.showSignature'] = 'Signatur anzeigen';
$this->items[$this->languageID]['wcf.message.settings.showSignature.description'] = 'Die im Profil eingestellte Signatur wird an diese Nachricht angehängt.';
?>