<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.user.login
* generated at Wed, 28 May 2014 19:41:18 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.login'] = 'Anmelden';
$this->items[$this->languageID]['wcf.user.login.error.password.false'] = 'Das eingegebene Kennwort ist falsch. Falls Sie Ihr Kennwort vergessen haben, steht Ihnen die <strong><a href="index.php?form=LostPassword{@SID_ARG_2ND}">&raquo;Kennwort vergessen&laquo;-Funktion</a></strong> zur Verfügung.';
$this->dynamicItems[$this->languageID]['wcf.user.login.error.password.false'] = 'Das eingegebene Kennwort ist falsch. Falls Sie Ihr Kennwort vergessen haben, steht Ihnen die <strong><a href="index.php?form=LostPassword<?php echo SID_ARG_2ND; ?>">&raquo;Kennwort vergessen&laquo;-Funktion</a></strong> zur Verfügung.';
$this->items[$this->languageID]['wcf.user.login.redirect'] = 'Sie wurden erfolgreich angemeldet.';
$this->items[$this->languageID]['wcf.user.login.useCookies'] = 'Ich möchte auf diesem Computer angemeldet bleiben, bis ich mich abmelde.';
?>