<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.user.usercp
* generated at Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.usercp'] = 'Profil bearbeiten';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.management'] = 'Verwaltung';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp'] = 'Moderation';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.profile'] = 'Profil';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.profile.account'] = 'Benutzerkonto';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.profile.personalDetails'] = 'Persönliche Daten';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.settings'] = 'Einstellungen';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.management.blacklist'] = 'Ignorierte Benutzer';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.management.whitelist'] = 'Freunde';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.profile.avatar'] = 'Avatar';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.management.attachment'] = 'Dateianhänge';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.profile.signature'] = 'Signatur';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.userGroups'] = 'Benutzergruppen';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.userGroups.leader'] = 'Gruppenleitung';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.userGroups.overview'] = 'Benutzergruppen';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.management.ignoredBoards'] = 'Foren an/aus';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.management.subscriptions'] = 'Abonnements';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.deletedPosts'] = 'Papierkorb (Beiträge)';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.deletedThreads'] = 'Papierkorb (Themen)';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.hiddenPosts'] = 'Freizuschaltende Beiträge';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.hiddenThreads'] = 'Freizuschaltende Themen';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.markedPosts'] = 'Markierte Beiträge';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.markedThreads'] = 'Markierte Themen';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.overview'] = 'Überblick';
$this->items[$this->languageID]['wcf.user.usercp.menu.link.modcp.reports'] = 'Gemeldete Beiträge';
?>