<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.acp.login
* generated at Wed, 28 May 2014 19:41:22 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.acp.login'] = 'Anmeldung';
$this->items[$this->languageID]['wcf.acp.login.data'] = 'Zugangsdaten';
?>