<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wbb.postAdd
* generated at Sun, 08 Jun 2014 22:15:40 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.postAdd.error.doublePostLock'] = 'Sie sind nicht berechtigt mehrere Antworten direkt hintereinander auf ein Thema abzugeben. Bitte bearbeiten Sie Ihren vorherigen Beitrag.';
$this->items[$this->languageID]['wbb.postAdd.error.doublePostLockTime'] = 'Sie sind nicht berechtigt innerhalb von {#$timeout} Minute(n) mehrere Antworten direkt hintereinander auf ein Thema abzugeben. Bitte bearbeiten Sie Ihren vorherigen Beitrag.';
$this->dynamicItems[$this->languageID]['wbb.postAdd.error.doublePostLockTime'] = 'Sie sind nicht berechtigt innerhalb von <?php echo StringUtil::formatNumeric($this->v[\'timeout\']); ?> Minute(n) mehrere Antworten direkt hintereinander auf ein Thema abzugeben. Bitte bearbeiten Sie Ihren vorherigen Beitrag.';
$this->items[$this->languageID]['wbb.postAdd.moderation.redirect'] = 'Ihre Antwort wurde erfolgreich gespeichert. Sie wird von einem Moderator überprüft und, falls keine Beanstandung vorliegt, für alle anderen Benutzer freigegeben.';
$this->items[$this->languageID]['wbb.postAdd.notification.mail'] = 'Hallo {$recipient}!
		
{$author} hat auf das Thema: "{$topic}" im Forum: "{$boardTitle}" auf der Website: "{PAGE_TITLE}" geantwortet.

Den neuen Beitrag erreichen Sie über den folgenden Link:
{PAGE_URL}/index.php?page=Thread&postID={$postID}#post{$postID}

{$author} hat folgenden Text geschrieben:
---------------------------------
{$text}
---------------------------------

Vielen Dank,
Ihr {PAGE_TITLE} Team';
$this->dynamicItems[$this->languageID]['wbb.postAdd.notification.mail'] = 'Hallo <?php echo StringUtil::encodeHTML($this->v[\'recipient\']); ?>!
		
<?php echo StringUtil::encodeHTML($this->v[\'author\']); ?> hat auf das Thema: "<?php echo StringUtil::encodeHTML($this->v[\'topic\']); ?>" im Forum: "<?php echo StringUtil::encodeHTML($this->v[\'boardTitle\']); ?>" auf der Website: "<?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>" geantwortet.

Den neuen Beitrag erreichen Sie über den folgenden Link:
<?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?page=Thread&postID=<?php echo StringUtil::encodeHTML($this->v[\'postID\']); ?>#post<?php echo StringUtil::encodeHTML($this->v[\'postID\']); ?>

<?php echo StringUtil::encodeHTML($this->v[\'author\']); ?> hat folgenden Text geschrieben:
---------------------------------
<?php echo StringUtil::encodeHTML($this->v[\'text\']); ?>
---------------------------------

Vielen Dank,
Ihr <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> Team';
$this->items[$this->languageID]['wbb.postAdd.notification.subject'] = 'Neuer Beitrag zum Thema: {$topic}';
$this->dynamicItems[$this->languageID]['wbb.postAdd.notification.subject'] = 'Neuer Beitrag zum Thema: <?php echo StringUtil::encodeHTML($this->v[\'topic\']); ?>';
$this->items[$this->languageID]['wbb.postAdd.oldThreadWarning'] = 'Achtung! Die letzte Antwort auf dieses Thema liegt mehr als {#$oldThreadWarning} Tage 
	zurück. Das Thema ist womöglich bereits veraltet. Bitte erstellen Sie ggf. ein <a href="index.php?form=ThreadAdd&amp;boardID={@$boardID}{@SID_ARG_2ND}">neues Thema</a>.';
$this->dynamicItems[$this->languageID]['wbb.postAdd.oldThreadWarning'] = 'Achtung! Die letzte Antwort auf dieses Thema liegt mehr als <?php echo StringUtil::formatNumeric($this->v[\'oldThreadWarning\']); ?> Tage 
	zurück. Das Thema ist womöglich bereits veraltet. Bitte erstellen Sie ggf. ein <a href="index.php?form=ThreadAdd&amp;boardID=<?php echo $this->v[\'boardID\']; ?><?php echo SID_ARG_2ND; ?>">neues Thema</a>.';
$this->items[$this->languageID]['wbb.postAdd.posts'] = '{if $posts|count == 1}Der erste Beitrag{else}Die letzten {#$posts|count} Beiträge{/if}';
$this->dynamicItems[$this->languageID]['wbb.postAdd.posts'] = '<?php if (count($this->v[\'posts\']) == 1) { ?>Der erste Beitrag<?php } else { ?>Die letzten <?php echo StringUtil::formatNumeric(count($this->v[\'posts\'])); ?> Beiträge<?php } ?>';
$this->items[$this->languageID]['wbb.postAdd.quote.subject'] = 'RE: {$subject}';
$this->dynamicItems[$this->languageID]['wbb.postAdd.quote.subject'] = 'RE: <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>';
$this->items[$this->languageID]['wbb.postAdd.redirect'] = 'Ihre Antwort wurde erfolgreich gespeichert. Sie werden zum Beitrag weitergeleitet.';
$this->items[$this->languageID]['wbb.postAdd.threadIsMarkedAsDone'] = 'Achtung! Dieses Thema wurde als erledigt markiert. Bitte erstellen Sie ggf. ein <a href="index.php?form=ThreadAdd&amp;boardID={@$boardID}{@SID_ARG_2ND}">neues Thema</a>.';
$this->dynamicItems[$this->languageID]['wbb.postAdd.threadIsMarkedAsDone'] = 'Achtung! Dieses Thema wurde als erledigt markiert. Bitte erstellen Sie ggf. ein <a href="index.php?form=ThreadAdd&amp;boardID=<?php echo $this->v[\'boardID\']; ?><?php echo SID_ARG_2ND; ?>">neues Thema</a>.';
$this->items[$this->languageID]['wbb.postAdd.title'] = 'Neue Antwort erstellen';
?>