<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wbb.acp.index
* generated at Wed, 28 May 2014 19:04:09 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.acp.index'] = 'WoltLab&reg; Burning Board&reg; Administrationsoberfläche';
$this->items[$this->languageID]['wbb.acp.index.credits'] = 'Über WoltLab&reg; Burning Board&reg;';
$this->items[$this->languageID]['wbb.acp.index.credits.contributor'] = 'Mitwirkende';
$this->items[$this->languageID]['wbb.acp.index.credits.designer'] = 'Design';
$this->items[$this->languageID]['wbb.acp.index.credits.developedBy'] = 'Software entwickelt von';
$this->items[$this->languageID]['wbb.acp.index.credits.developer'] = 'Programmierung';
$this->items[$this->languageID]['wbb.acp.index.credits.productManager'] = 'Projektleitung';
$this->items[$this->languageID]['wbb.acp.index.credits.trademarks'] = '&raquo;WoltLab&reg;&laquo; und &raquo;Burning Board&reg;&laquo; sind eingetragene Gemeinschaftsmarken beim europäischen Harmonisierungsamt für den Binnenmarkt (OHIM) in Alicante, Spanien.';
$this->items[$this->languageID]['wbb.acp.index.credits.translators'] = 'Übersetzung';
$this->items[$this->languageID]['wbb.acp.index.news'] = 'Nachrichten';
$this->items[$this->languageID]['wbb.acp.index.searchUsers'] = 'Schnellsuche nach Benutzern';
$this->items[$this->languageID]['wbb.acp.index.stat'] = 'Statistik';
$this->items[$this->languageID]['wbb.acp.index.stat.attachments'] = 'Dateianhänge';
$this->items[$this->languageID]['wbb.acp.index.stat.database.entries'] = 'Datenbankeinträge';
$this->items[$this->languageID]['wbb.acp.index.stat.database.size'] = 'Datenbankgröße';
$this->items[$this->languageID]['wbb.acp.index.stat.members'] = 'Mitglieder';
$this->items[$this->languageID]['wbb.acp.index.stat.posts'] = 'Beiträge';
$this->items[$this->languageID]['wbb.acp.index.stat.postsPerDay'] = '({#$postsPerDay} Beiträge pro Tag)';
$this->dynamicItems[$this->languageID]['wbb.acp.index.stat.postsPerDay'] = '(<?php echo StringUtil::formatNumeric($this->v[\'postsPerDay\']); ?> Beiträge pro Tag)';
$this->items[$this->languageID]['wbb.acp.index.stat.privateMessages'] = 'Private Nachrichten';
$this->items[$this->languageID]['wbb.acp.index.stat.threads'] = 'Themen';
$this->items[$this->languageID]['wbb.acp.index.stat.threadsPerDay'] = '({#$threadsPerDay} Themen pro Tag)';
$this->dynamicItems[$this->languageID]['wbb.acp.index.stat.threadsPerDay'] = '(<?php echo StringUtil::formatNumeric($this->v[\'threadsPerDay\']); ?> Themen pro Tag)';
$this->items[$this->languageID]['wbb.acp.index.stat.usersOnline'] = 'Benutzer online';
$this->items[$this->languageID]['wbb.acp.index.system'] = 'System';
$this->items[$this->languageID]['wbb.acp.index.system.cache'] = 'Cache';
$this->items[$this->languageID]['wbb.acp.index.system.exportInformation'] = 'System-Informationen herunterladen';
$this->items[$this->languageID]['wbb.acp.index.system.installationDate'] = 'Installationsdatum';
$this->items[$this->languageID]['wbb.acp.index.system.load'] = 'Aktueller UNIX Load';
$this->items[$this->languageID]['wbb.acp.index.system.os'] = 'Betriebssystem';
$this->items[$this->languageID]['wbb.acp.index.system.php'] = 'PHP Version';
$this->items[$this->languageID]['wbb.acp.index.system.server'] = 'Server';
$this->items[$this->languageID]['wbb.acp.index.system.software'] = 'Software';
$this->items[$this->languageID]['wbb.acp.index.system.sql.type'] = 'Datenbank';
$this->items[$this->languageID]['wbb.acp.index.system.sql.version'] = 'MySQL Version';
$this->items[$this->languageID]['wbb.acp.index.system.wbb.version'] = 'Burning Board&reg; Version';
$this->items[$this->languageID]['wbb.acp.index.system.wcf.version'] = 'Community Framework&trade; Version';
$this->items[$this->languageID]['wbb.acp.index.system.webserver'] = 'Webserver';
$this->items[$this->languageID]['wbb.acp.index.updates'] = 'Updates';
$this->items[$this->languageID]['wbb.acp.index.minorUpdates'] = 'Wichtige Updates';
$this->items[$this->languageID]['wbb.acp.index.minorUpdates.description'] = 'Es stehen derzeit folgende wichtige Updates zur Verfügung:';
$this->items[$this->languageID]['wbb.acp.index.majorUpdates'] = 'Optionale Updates';
$this->items[$this->languageID]['wbb.acp.index.majorUpdates.description'] = 'Es stehen derzeit folgende optionale Updates zur Verfügung:';
$this->items[$this->languageID]['wbb.acp.index.updates.startUpdate'] = 'Update jetzt durchführen';
$this->items[$this->languageID]['wbb.acp.index.updates.update'] = '{$update.packageName}{if $update.instanceNo > 1} (#{$update.instanceNo}){/if} Version {$update.version.packageVersion}';
$this->dynamicItems[$this->languageID]['wbb.acp.index.updates.update'] = '<?php echo StringUtil::encodeHTML($this->v[\'update\'][\'packageName\']); ?><?php if ($this->v[\'update\'][\'instanceNo\'] > 1) { ?> (#<?php echo StringUtil::encodeHTML($this->v[\'update\'][\'instanceNo\']); ?>)<?php } ?> Version <?php echo StringUtil::encodeHTML($this->v[\'update\'][\'version\'][\'packageVersion\']); ?>';
?>