<?php
/**
* WoltLab Community Framework
* Template: wysiwyg
* Compiled at: Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'wysiwyg';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/Wysiwyg.class.js"></script>
<script type="text/javascript">
//<![CDATA[
// language
var language = new Object();
language['undo.desc'] = "Rückgängig";language['redo.desc'] = "Wiederherstellen";
language['b.desc'] = "Fett";language['i.desc'] = "Kursiv";language['u.desc'] = "Unterstreichen";language['s.desc'] = "Durchstreichen";
language['toolbar.focus'] = "Werkzeugleiste auswählen";
language['link.desc'] = "Link einfügen";language['link.insert.url'] = "Geben Sie die volle Adresse des Links ein:";language['link.insert.url.optional']= "Geben Sie die volle Adresse des Links ein (optional):";language['link.insert.name'] = "Geben Sie einen Linknamen ein (optional):";language['unlink.desc'] = "Link entfernen";language['insertText'] = "Geben Sie den zu formatierenden Text ein (optional).";
language['textAlignLeft.desc'] = "Linksbündig";language['textAlignCenter.desc'] = "Zentrieren";language['textAlignRight.desc'] = "Rechtsbündig";language['textJustify.desc'] = "Blocksatz";
language['bullist.desc'] = "Liste";language['numlist.desc'] = "Nummerierte Liste";
language['cut.desc'] = "Ausschneiden";language['copy.desc'] = "Kopieren";language['paste.desc'] = "Einfügen";
language['img.desc'] = "Bild einfügen";language['image.insert'] = "Geben Sie hier die Adresse (URL) des Bildes ein.";
language['color.desc'] = "Schriftfarbe";language['fontsize.default'] = "Schriftgröße";language['fontFamily.default'] = "Schriftart";
language['quotation.desc'] = "Anführungszeichen einfügen";language['quote.desc'] = "Zitat einfügen";language['code.desc'] = "Code einfügen";
language['view.wysiwyg'] = "Editor";language['view.code'] = "Quellcode";
language['noFormElement'] = "Es ist kein Element vorhanden, das zu einem WYSIWYG-Editor gewandelt werden kann.";language['extraBBCodeNotValid'] = "Ihre Eingabe ist nicht korrekt."; 

// language direction
var languageDirection = "ltr";

// smileys
var smilies = new Object();
<?php
if (count($this->v['defaultSmileys']) > 0) {
foreach ($this->v['defaultSmileys'] as $this->v['smiley']) {
?>
	smilies['<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['smiley']->smileyCode), $this); ?>'] = new Array('<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['smiley']->getURL()), $this); ?>', '<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['smiley']->smileyTitle), $this); ?><?php $_lang3d24d2fceb4200e4d0b118586af9d8a14bf5e747 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang3d24d2fceb4200e4d0b118586af9d8a14bf5e747, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>');
<?php } } ?>

// bbcodes
var coreBBCodes = new Object();
var extraBBCodes = new Object();
var sourceCodes = new Object();
<?php if (isset($this->v['wysiwygBBCodes']) && count($this->v['wysiwygBBCodes']) > 0) { ?>
	<?php
if (count($this->v['wysiwygBBCodes']) > 0) {
foreach ($this->v['wysiwygBBCodes'] as $this->v['bbCode']) {
?>
		var tmpBBCode = { wysiwyg:<?php echo $this->v['bbCode']['wysiwyg']; ?>, bbCode:'<?php echo $this->v['bbCode']['bbcodeTag']; ?>', htmlOpen:'<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['bbCode']['htmlOpen']), $this); ?>', htmlClose:'<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['bbCode']['htmlClose']), $this); ?>', icon:'<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['bbCode']['wysiwygIcon']), $this); ?>', sourceCode:<?php echo $this->v['bbCode']['sourceCode']; ?>, attributes:[<?php
$_lengthf27c31ada3cbcb2a20d32ef9025f55ed889a7484 = count($this->v['bbCode']['attributes']);
$_if27c31ada3cbcb2a20d32ef9025f55ed889a7484 = 0;
foreach ($this->v['bbCode']['attributes'] as $this->v['attribute']) { ?>{ attributeHTML:'<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['attribute']['attributeHtml']), $this); ?>', validationPattern:'<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['attribute']['validationPattern']), $this); ?>', required:<?php echo $this->v['attribute']['required']; ?> }<?php
if (++$_if27c31ada3cbcb2a20d32ef9025f55ed889a7484 < $_lengthf27c31ada3cbcb2a20d32ef9025f55ed889a7484) { echo ', '; }
} ?>] };
		<?php if ($this->v['bbCode']['isCoreBBCode']) { ?>coreBBCodes['<?php echo $this->v['bbCode']['bbcodeTag']; ?>'] = tmpBBCode;<?php } else { ?>extraBBCodes['<?php echo $this->v['bbCode']['bbcodeTag']; ?>'] = tmpBBCode;<?php } ?>
		<?php if ($this->v['bbCode']['sourceCode']) { ?>sourceCodes['<?php echo $this->v['bbCode']['bbcodeTag']; ?>'] = '<?php echo $this->v['bbCode']['bbcodeTag']; ?>';<?php } ?>
		language['<?php echo $this->v['bbCode']['bbcodeTag']; ?>.title'] = "<?php ob_start(); ?>wcf.bbcode.<?php echo $this->v['bbCode']['bbcodeTag']; ?>.title<?php $_lang3e939838998427e4f473e35d6e01f9272f838225 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->get($_lang3e939838998427e4f473e35d6e01f9272f838225); ?>";
		<?php
if (count($this->v['bbCode']['attributes']) > 0) {
foreach ($this->v['bbCode']['attributes'] as $this->v['index'] => $this->v['attribute']) {
?>
			language['<?php echo $this->v['bbCode']['bbcodeTag']; ?>.attribute<?php echo $this->v['index']+1; ?>.promptText'] = "<?php ob_start(); ?>wcf.bbcode.<?php echo $this->v['bbCode']['bbcodeTag']; ?>.promptText<?php $_langda70e5209b184464e44c43aa4448ebb7d2c816b4 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->get($_langda70e5209b184464e44c43aa4448ebb7d2c816b4); ?>";
		<?php } } ?>
	<?php } } ?>
<?php } ?>
<?php if (isset($this->v['errorField']) && $this->v['errorField'] == 'text') { ?>errorField = true;<?php } else { ?>errorField = false;<?php } ?>

// build editor. pass neccessary variables
tinyMCE.init({
	// set active view flag (code or wysiwyg) ($editorIsActive) (default:wysiwyg)
	editorIsActive : <?php if (isset($this->v['wysiwygEditorMode'])) { ?><?php echo $this->v['wysiwygEditorMode']; ?><?php } else { ?>1<?php } ?>,
	
	// set available views (default: both views available)
	editorEnableWysiwygView : <?php if (isset($this->v['editorEnableWysiwygView'])) { ?><?php echo $this->v['editorEnableWysiwygView']; ?><?php } else { ?>1<?php } ?>,
	editorEnableCodeView : <?php if (isset($this->v['editorEnableCodeView'])) { ?><?php echo $this->v['editorEnableCodeView']; ?><?php } else { ?>1<?php } ?>,	
		
	// set some url vars
	iconURL : "<?php echo RELATIVE_WCF_DIR; ?>icon/",
	imageURL : "<?php echo RELATIVE_WCF_DIR; ?>icon/wysiwyg/",
	blankHTML : "<?php echo RELATIVE_WCF_DIR; ?>js/blank.htm",
	cssFile : "<?php echo RELATIVE_WCF_DIR; ?>style/style-<?php echo $this->v['this']->getStyle()->styleID; ?>.css",
		
	// set editor height var ($wysiwygHeight)
	height: <?php if (isset($this->v['wysiwygEditorHeight'])) { ?><?php echo $this->v['wysiwygEditorHeight']; ?><?php } else { ?>-1<?php } ?>,
	
	// set page default font color var
	defaultPageFontColor: '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['this']->getStyle()->getVariable('page.font.color')), $this); ?>'
});
//]]>
</script>