<?php
/**
* WoltLab Community Framework
* Template: userProfileEdit
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userProfileEdit';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><?php
$outerTemplateNamedb1f612e1363d4f0f38960ff67ad88256a367f52 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamedb1f612e1363d4f0f38960ff67ad88256a367f52;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.category.<?php echo StringUtil::encodeHTML($this->v['category']); ?><?php $_lang3e58e1aecd3359981b03da86a90e9d50fa862394 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang3e58e1aecd3359981b03da86a90e9d50fa862394, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> - Profil bearbeiten - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang76263727b4e4cad427f2ea03bb69aea4a4f35763 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang76263727b4e4cad427f2ea03bb69aea4a4f35763, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName9661b25dea7dcc325da71c5b1321e2e709df0675 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName9661b25dea7dcc325da71c5b1321e2e709df0675;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateNamef21332bf87d8767083f4786a4ca765bb6e39c2ac = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamef21332bf87d8767083f4786a4ca765bb6e39c2ac;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<?php ob_start(); ?>
		<?php if ($this->v['errorField']) { ?>
			<p class="error">Ihre Angaben sind ungültig. Bitte überprüfen Sie die markierten Eingabefelder.</p>
		<?php } ?>
		
		<?php if (isset($this->v['success'])) { ?>
			<p class="success">Ihre Einstellungsänderungen wurden erfolgreich gespeichert.</p>
		<?php } ?>
	<?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->append('userMessages', $this->v['tpl']['capture']['default']);
?>
	
	<?php
$outerTemplateNamed6c2a6d810832311d65b66dc7517d37fd17b5d56 = $this->v['tpl']['template'];
$this->includeTemplate("userCPHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamed6c2a6d810832311d65b66dc7517d37fd17b5d56;
$this->v['tpl']['includedTemplates']["userCPHeader"] = 1;
?>
	
	<form method="post" action="index.php?form=UserProfileEdit">
		<div class="border tabMenuContent">
			<div class="container-1">
				<h3 class="subHeadline"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.category.<?php echo StringUtil::encodeHTML($this->v['category']); ?><?php $_lang42cb12d8de299f415e1b2ee2d17a8f7cff7fdce2 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang42cb12d8de299f415e1b2ee2d17a8f7cff7fdce2, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></h3>
				
				<?php echo SID_INPUT_TAG; ?>
				<input type="hidden" name="category" value="<?php echo StringUtil::encodeHTML($this->v['category']); ?>" />
				
				<?php if ($this->v['category'] == 'settings.general' && count($this->v['availableLanguages']) > 1) { ?>
					<fieldset>
						<legend><label for="languageID">Sprache</label></legend>
						<div class="formElement">
							<div class="formFieldLabel">
								<label for="languageID">Sprache</label>
							</div>
							<div class="formField">
								<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['availableLanguages'], 'selected' => $this->v['languageID'], 'name' => 'languageID', 'id' => 'languageID', 'disableEncoding' => true), $this); ?>
							</div>
							<div class="formFieldDesc">
								<p>Bitte wählen Sie aus, in welcher Sprache die Benutzeroberfläche erscheinen soll!</p>
							</div>
						</div>
						
						<?php if (count($this->v['availableContentLanguages']) > 1) { ?>
							<div class="formGroup">
								<div class="formGroupLabel">
									<label>Zeige Inhalte in folgenden Sprachen an</label>
								</div>
								<div class="formGroupField">
									<fieldset>
										<legend class="formFieldLabel">
											<label>Zeige Inhalte in folgenden Sprachen an</label>
										</legend>
										<div class="formField">
											<ul class="formOptions">
												<?php
if (count($this->v['availableContentLanguages']) > 0) {
foreach ($this->v['availableContentLanguages'] as $this->v['availableLanguageID'] => $this->v['availableLanguage']) {
?>
													<li><label><input type="checkbox" name="visibleLanguages[]" value="<?php echo $this->v['availableLanguageID']; ?>"<?php if (in_array($this->v['availableLanguageID'],$this->v['visibleLanguages'])) { ?> checked="checked"<?php } ?> /> <?php echo $this->v['availableLanguage']; ?></label></li>
												<?php } } ?>
											</ul>
										</div>
										<div class="formFieldDesc">
											<p>Geben Sie an, in welchen Sprachen erstellte Inhalte angezeigt werden sollen.</p>
										</div>
									</fieldset>
								</div>
							</div>
						<?php } ?>
					</fieldset>
				<?php } ?>
				
				<?php if ($this->v['category'] == 'settings.display' && count($this->v['availableStyles']) > 1) { ?>
					<fieldset>
						<legend><label for="styleID">Individueller Stil</label></legend>
						<div class="formElement">
							<div class="formFieldLabel">
								<label for="styleID">Individueller Stil</label>
							</div>
							<div class="formField">
								<select name="styleID" id="styleID" onchange="showStylePreviewImage(this)" onkeyup="showStylePreviewImage(this)">
									<option value="0"></option>
									<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['availableStyles'], 'selected' => $this->v['styleID']), $this); ?>
								</select>
							</div>
							<div class="formFieldDesc">
								<p>Sie können aus mehreren Stilen Ihren individuellen Stil für die Benutzeroberfläche auswählen.</p>
								<div id="stylePreviewImageContainer" class="stylePreviewImageContainer"></div>
							</div>
							
							<script type="text/javascript">
								//<![CDATA[
								var stylePreviewImages = new Array();
								<?php
if (count($this->v['availableStyles']) > 0) {
foreach ($this->v['availableStyles'] as $this->v['availableStyle']) {
?><?php if ($this->v['availableStyle']->image) { ?>stylePreviewImages[<?php echo $this->v['availableStyle']->styleID; ?>] = '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['availableStyle']->image), $this); ?>';<?php } ?><?php } } ?>
								function showStylePreviewImage(styleSelect) {
									// remove image
									var stylePreviewImageContainer = document.getElementById('stylePreviewImageContainer');
									for (var i = stylePreviewImageContainer.childNodes.length - 1; i >= 0; i--) {
										stylePreviewImageContainer.removeChild(stylePreviewImageContainer.childNodes[i]);
									}
									
									if (styleSelect.selectedIndex != -1) {
										var styleID = styleSelect.options[styleSelect.selectedIndex].value
										if (stylePreviewImages[styleID]) {
											var image = document.createElement('img');
											stylePreviewImageContainer.appendChild(image);
											image.src = RELATIVE_WCF_DIR + stylePreviewImages[styleID];
										}
									}
								}
								
								onloadEvents.push(function() { showStylePreviewImage(document.getElementById('styleID')) });
								//]]>
							</script>
						</div>
					</fieldset>
				<?php } ?>
				
				<?php
if (count($this->v['optionCategories']) > 0) {
foreach ($this->v['optionCategories'] as $this->v['category']) {
?>
					<fieldset>
						<legend><?php if ($this->v['category']['categoryIconM']) { ?><img src="<?php ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['category']['categoryIconM']); ?><?php $_icon7dff861bb73fe744119d9d3b1795ae74aa32b6c5 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon7dff861bb73fe744119d9d3b1795ae74aa32b6c5); ?>" alt="" /> <?php } ?><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.category.<?php echo StringUtil::encodeHTML($this->v['category']['categoryName']); ?><?php $_lange8d494b7f80824aaa9de6ab4e1bfa27ab635c8c5 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lange8d494b7f80824aaa9de6ab4e1bfa27ab635c8c5, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></legend>
						
						<?php
$outerTemplateName3e9e0bccd95ece53d252c5716a716829f6e326f8 = $this->v['tpl']['template'];
$this->includeTemplate('userOptionFieldList', array('options' => $this->v['category']['options']), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName3e9e0bccd95ece53d252c5716a716829f6e326f8;
$this->v['tpl']['includedTemplates']['userOptionFieldList'] = 1;
?>
						
					</fieldset>
				<?php } } ?>
				
				<?php if (count($this->v['options']) > 0) { ?>
					<?php
$outerTemplateNameea2b9569d91b6365ce0cb00b83653dbeaae8f2a1 = $this->v['tpl']['template'];
$this->includeTemplate('userOptionFieldList', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameea2b9569d91b6365ce0cb00b83653dbeaae8f2a1;
$this->v['tpl']['includedTemplates']['userOptionFieldList'] = 1;
?>
				<?php } ?>
				
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
			</div>
		</div>
		<div class="formSubmit">
			<input type="submit" accesskey="s" value="Absenden" />
			<input type="reset" accesskey="r" value="Zurücksetzen" />
		</div>
	</form>

</div>

<?php
$outerTemplateName426343639687c256f135198b562931ea277eeb2f = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName426343639687c256f135198b562931ea277eeb2f;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>