<?php
/**
* WoltLab Community Framework
* Template: userOptionFieldList
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userOptionFieldList';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierConcat'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierConcat.class.php');
$this->pluginObjects['TemplatePluginModifierConcat'] = new TemplatePluginModifierConcat;
}
?><?php
if (count($this->v['options']) > 0) {
foreach ($this->v['options'] as $this->v['option']) {
?>
	<?php $this->assign('divClass', ''); ?>
	<?php if (isset($this->v['option']['divClass'])) { ?>
		<?php if ($this->v['divClass']) { ?>
			<?php $this->assign('divClass', "{$this->v['divClass']} "); ?>
		<?php } ?>
		
		<?php $this->assign('divClass', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['divClass'],$this->v['option']['divClass']), $this)); ?>
	<?php } ?>
	
	<?php if (is_array($this->v['errorType']) && isset($this->v['errorType'][$this->v['option']['optionName']])) { ?>
		<?php $this->assign('error', $this->v['errorType'][$this->v['option']['optionName']]); ?>
		<?php if ($this->v['divClass']) { ?>
			<?php $this->assign('divClass', "{$this->v['divClass']} "); ?>
		<?php } ?>
		
		<?php $this->assign('divClass', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['divClass'],'formError'), $this)); ?>
	<?php } else { ?>
		<?php $this->assign('error', ''); ?>
	<?php } ?>
	
	
	<?php if (isset($this->v['option']['isOptionGroup'])) { ?>
		<div class="<?php if ($this->v['divClass']) { ?><?php echo StringUtil::encodeHTML($this->v['divClass']); ?> <?php } ?>formGroup" id="<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?>Div">
			<div class="formGroupLabel">
				<label><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?><?php $_lang66daad05c7de5e8ed21adb11d2bb07dcb00aa0b0 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang66daad05c7de5e8ed21adb11d2bb07dcb00aa0b0, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></label>
			</div>
			<div class="formGroupField">
				<fieldset>
					<legend><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?><?php $_lang51522241f8d789d6603eec513f7939a492185fb2 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang51522241f8d789d6603eec513f7939a492185fb2, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></legend>
						
					<div class="formField">
						<?php echo $this->v['option']['html']; ?>
						<?php if (isset($this->v['option']['supportsExactMatch'])) { ?>
							<label><input type="checkbox" name="matchExactly[<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?>]" value="1" <?php if (isset($this->v['matchExactly'][$this->v['option']['optionName']])) { ?>checked="checked" <?php } ?>/> Exakter Treffer</label>
						<?php } ?>
					</div>
					
					<?php if ( ! isset($this->v['hideDescription'])) { ?>
						<div class="formFieldDesc">
							<p><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?>.description<?php $_langa44169b97f7baa6ebabde03f8358389738756160 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langa44169b97f7baa6ebabde03f8358389738756160, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>
						</div>
					<?php } ?>
					
					<?php if ($this->v['error']) { ?>
						<p class="innerError">
							<?php if ($this->v['error'] == 'empty') { ?>
								Bitte füllen Sie dieses Eingabefeld aus.
							<?php } else { ?>	
								<?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.error.<?php echo StringUtil::encodeHTML($this->v['error']); ?><?php $_lang02a14a0816aa34dccbefb1ffa873406c2f0426de = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang02a14a0816aa34dccbefb1ffa873406c2f0426de, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>
							<?php } ?>
						</p>
					<?php } ?>
					
				</fieldset>
			</div>
		</div>
		
	<?php } else { ?>
		<div class="<?php if ($this->v['divClass']) { ?><?php echo StringUtil::encodeHTML($this->v['divClass']); ?> <?php } ?>formElement" id="<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?>Div">
			<?php ob_start(); ?>
				<?php if ($this->v['error']) { ?>
					<p class="innerError">
						<?php if ($this->v['error'] == 'empty') { ?>
							Bitte füllen Sie dieses Eingabefeld aus.
						<?php } else { ?>	
							<?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.error.<?php echo StringUtil::encodeHTML($this->v['error']); ?><?php $_lang59867bc3cb840e57d7b11a15245b81d4d458b4b5 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang59867bc3cb840e57d7b11a15245b81d4d458b4b5, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>
						<?php } ?>
					</p>
				<?php } ?>
			<?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->assign('innerError', $this->v['tpl']['capture']['default']);
?>
			
			<?php if ($this->v['option']['beforeLabel']) { ?>
				<div class="formField">
					<label for="<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?>"><?php echo $this->v['option']['html']; ?> <?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?><?php $_lang9c7491c99401026b337f037cb00a1dbfcd9016d5 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang9c7491c99401026b337f037cb00a1dbfcd9016d5, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></label>
					<?php echo $this->v['innerError']; ?>
				</div>
			<?php } else { ?>
				<div class="formFieldLabel">
					<label for="<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?>"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?><?php $_lang78fba3ae64128cf65f3615c1f2bcc3515e57bda3 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang78fba3ae64128cf65f3615c1f2bcc3515e57bda3, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></label>
				</div>
				<div class="formField">
					<?php echo $this->v['option']['html']; ?>
					<?php echo $this->v['innerError']; ?>			
				</div>
			<?php } ?>
			
			<?php if ( ! isset($this->v['hideDescription'])) { ?>
				<div class="formFieldDesc">
					<p><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?>.description<?php $_langbaba130dcda5bf1203671835215a680c713d3efc = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langbaba130dcda5bf1203671835215a680c713d3efc, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>
				</div>
			<?php } ?>
		</div>
	<?php } ?>
	
	<script type="text/javascript">
		//<![CDATA[
		<?php if (isset($this->v['option']['enableOptionsJS'])) { ?>onloadEvents.push(function() { <?php echo $this->v['option']['enableOptionsJS']; ?>; });<?php } ?>
		//]]>
	</script>
<?php } } ?>