<?php
/**
* WoltLab Community Framework
* Template: userCPHeader
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userCPHeader';
?>
<ul class="breadCrumbs">
	<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langb44a2ee794a76a7348b9859fcbc1519ff3844cd7 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langb44a2ee794a76a7348b9859fcbc1519ff3844cd7, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
</ul>
<div class="mainHeadline">
	<img src="<?php echo StyleManager::getStyle()->getIconPath('profileEditL.png'); ?>" alt="" />
	<div class="headlineContainer">
		<h2>Profil bearbeiten</h2>
	</div>
</div>

<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>

<div id="profileEditContent" class="tabMenu">
	<ul>
		<?php
if (count($this->v['this']->getUserCPMenu()->getMenuItems('')) > 0) {
foreach ($this->v['this']->getUserCPMenu()->getMenuItems('') as $this->v['item']) {
?>
			<li<?php if (in_array($this->v['item']['menuItem'],$this->v['this']->getUserCPMenu()->getActiveMenuItems())) { ?> class="activeTabMenu"<?php } ?>><a href="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemLink']); ?>"><?php if ($this->v['item']['menuItemIcon']) { ?><img src="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemIcon']); ?>" alt="" /> <?php } ?><span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_langcf2009119b3ea48fcd2079bc1cff0d552ce25e4e = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langcf2009119b3ea48fcd2079bc1cff0d552ce25e4e, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a></li>
		<?php } } ?>
	</ul>
</div>
<div class="subTabMenu">
	<div class="containerHead">
		<?php $this->assign('activeMenuItem', $this->v['this']->getUserCPMenu()->getActiveMenuItem()); ?>
		<?php if ($this->v['activeMenuItem'] && count($this->v['this']->getUserCPMenu()->getMenuItems($this->v['activeMenuItem']))) { ?>
			<ul>
				<?php
if (count($this->v['this']->getUserCPMenu()->getMenuItems($this->v['activeMenuItem'])) > 0) {
foreach ($this->v['this']->getUserCPMenu()->getMenuItems($this->v['activeMenuItem']) as $this->v['item']) {
?>
					<li<?php if (in_array($this->v['item']['menuItem'],$this->v['this']->getUserCPMenu()->getActiveMenuItems())) { ?> class="activeSubTabMenu"<?php } ?>><a href="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemLink']); ?>"><?php if ($this->v['item']['menuItemIcon']) { ?><img src="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemIcon']); ?>" alt="" /> <?php } ?><span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_lang26207e4b4d02fb834b1e4b97f629e864b027ddfb = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang26207e4b4d02fb834b1e4b97f629e864b027ddfb, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a></li>
				<?php } } ?>
			</ul>
		<?php } else { ?>
			<div> </div>
		<?php } ?>
	</div>
</div>