<?php
/**
* WoltLab Community Framework
* Template: login
* Compiled at: Sun, 08 Jun 2014 22:05:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'login';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><?php
$outerTemplateName07815739cd1cc617bf9aa470cb10768070eeb3f9 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName07815739cd1cc617bf9aa470cb10768070eeb3f9;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Anmelden - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langdffcf672b7bc639deddf45542079ae8201633850 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langdffcf672b7bc639deddf45542079ae8201633850, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateNamee6c94e6492054a99779e2552b0e2e75eb7bff070 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamee6c94e6492054a99779e2552b0e2e75eb7bff070;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateName195ef4184887fdca5ec3312fafdf39223b4c1172 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName195ef4184887fdca5ec3312fafdf39223b4c1172;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<script type="text/javascript">
		//<![CDATA[
		onloadEvents.push(function() { if (!'<?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['username']), $this)); ?>' || '<?php echo StringUtil::encodeHTML($this->v['errorField']); ?>' == 'username') document.getElementById('loginUsername').focus(); else document.getElementById('loginPassword').focus(); });
		//]]>
	</script>
	
	<ul class="breadCrumbs">
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang319063a81f9abee1ebe4ad7d35041d98a6f88f59 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang319063a81f9abee1ebe4ad7d35041d98a6f88f59, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	</ul>
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('loginL.png'); ?>" alt="" />
		<div class="headlineContainer">
			<h2> Anmelden</h2>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php if ($this->v['errorField']) { ?>
		<p class="error">Ihre Angaben sind ungültig. Bitte überprüfen Sie die markierten Eingabefelder.</p>
	<?php } ?>
	
	<form method="post" action="index.php?form=UserLogin">
		<div class="border content">
			<div class="container-1">
				<div class="formElement<?php if ($this->v['errorField'] == 'username') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="loginUsername">Benutzername</label>
					</div>
					<div class="formField">
						<input type="text" class="inputText" name="loginUsername" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" id="loginUsername" />
						<?php if ($this->v['errorField'] == 'username') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
								<?php if ($this->v['errorType'] == 'notFound') { ?>Der Benutzername &raquo;<?php echo StringUtil::encodeHTML($this->v['username']); ?>&laquo; konnte nicht gefunden werden.<?php } ?>
								<?php if ($this->v['errorType'] == 'notEnabled') { ?>wcf.user.login.error.username.notEnabled<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
				
				<div class="formElement<?php if ($this->v['errorField'] == 'password') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="loginPassword">Kennwort</label>
					</div>
					<div class="formField">
						<input type="password" class="inputText" name="loginPassword" value="<?php echo StringUtil::encodeHTML($this->v['password']); ?>" id="loginPassword" />
						<?php if ($this->v['errorField'] == 'password') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
								<?php if ($this->v['errorType'] == 'false') { ?>Das eingegebene Kennwort ist falsch. Falls Sie Ihr Kennwort vergessen haben, steht Ihnen die <strong><a href="index.php?form=LostPassword<?php echo SID_ARG_2ND; ?>">&raquo;Kennwort vergessen&laquo;-Funktion</a></strong> zur Verfügung.<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
				
				<?php if ($this->v['supportsPersistentLogins']) { ?>
					<div class="formElement">
						<div class="formField">
							<label><input type="checkbox" name="useCookies" value="1" <?php if ($this->v['useCookies'] == 1) { ?>checked="checked" <?php } ?>/> Ich möchte auf diesem Computer angemeldet bleiben, bis ich mich abmelde.</label>
						</div>
					</div>
				<?php } ?>
				
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
				<?php
$outerTemplateNameef30273101903a981c2545c3cc8ab8a98a29e16c = $this->v['tpl']['template'];
$this->includeTemplate('captcha', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameef30273101903a981c2545c3cc8ab8a98a29e16c;
$this->v['tpl']['includedTemplates']['captcha'] = 1;
?>
				
				<div class="formElement">
					<div class="formField">
						<ul class="formOptionsLong">
							<li><img src="<?php echo StyleManager::getStyle()->getIconPath('lostPasswordS.png'); ?>" alt="" /> <a href="index.php?form=LostPassword<?php echo SID_ARG_2ND; ?>">Kennwort vergessen</a></li>
							<?php if ( ! REGISTER_DISABLED && REGISTER_ACTIVATION_METHOD == 1) { ?><li><img src="<?php echo StyleManager::getStyle()->getIconPath('registerS.png'); ?>" alt="" /> <a href="index.php?page=Register&amp;action=enable<?php echo SID_ARG_2ND; ?>">Abschließen der Registrierung</a></li><?php } ?>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
			
		<div class="formSubmit">
			<input type="submit" accesskey="s" value="Absenden" />
			<input type="reset" accesskey="r" value="Zurücksetzen" />
		</div>
		
		<input type="hidden" name="url" value="<?php echo StringUtil::encodeHTML($this->v['url']); ?>" />
		<?php echo SID_INPUT_TAG; ?>
	</form>

</div>

<?php
$outerTemplateName7489ef2a6832aa9685f623c04ba3da754dbe24a6 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7489ef2a6832aa9685f623c04ba3da754dbe24a6;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>