<?php
/**
* WoltLab Community Framework
* Template: userProfileEditRankSelect
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userProfileEditRankSelect';
?>
<ul class="formOptionsLong">
	<?php
if (count($this->v['ranks']) > 0) {
foreach ($this->v['ranks'] as $this->v['rank']) {
?>
		<li><label><input type="radio" name="rankID" value="<?php echo $this->v['rank']->rankID; ?>" <?php if ($this->v['rankID'] == $this->v['rank']->rankID) { ?>checked="checked" <?php } ?>/> <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['rank']->rankTitle); ?><?php $_lang1c875faf7c28e4fef641a20bad465854ef261501 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang1c875faf7c28e4fef641a20bad465854ef261501, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> <?php echo $this->v['rank']->getImage(); ?></label></li>
	<?php } } ?>
</ul>