<?php
/**
* WoltLab Community Framework
* Template: optionTypeDate
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'optionTypeDate';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
?><div class="floatContainer">
	<?php
if (count($this->v['dateInputOrder']) > 0) {
foreach ($this->v['dateInputOrder'] as $this->v['element']) {
?>
		<div class="floatedElement">
			<label for="<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?><?php echo StringUtil::encodeHTML(ucfirst($this->v['element'])); ?>"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.global.date.<?php echo StringUtil::encodeHTML($this->v['element']); ?><?php $_lang0e4d9b4712b406ad8a83e543e035310734d65aff = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang0e4d9b4712b406ad8a83e543e035310734d65aff, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></label>
			
			<?php if ($this->v['element'] == 'day') { ?>
				<select id="<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>Day" name="values[<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>][day]">
					<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['days'], 'selected' => $this->v['day']), $this); ?>
				</select>
			<?php } ?>
			
			<?php if ($this->v['element'] == 'month') { ?>
				<select id="<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>Month" name="values[<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>][month]">
					<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['months'], 'selected' => $this->v['month']), $this); ?>
				</select>
			<?php } ?>
			
			<?php if ($this->v['element'] == 'year') { ?>
				<input id="<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>Year" class="inputText fourDigitInput" type="text" name="values[<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>][year]" value="<?php echo StringUtil::encodeHTML($this->v['year']); ?>" maxlength="4" />
			<?php } ?>
		</div>
	<?php } } ?>
</div>
<?php if ( ! $this->v['yearRequired']) { ?>
	<p class="smallFont light">Die Angabe des Jahres ist optional.</p>
<?php } ?>