<?php
/**
* WoltLab Community Framework
* Template: optionTypeText
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'optionTypeText';
?>
<input id="<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>" type="<?php echo $this->v['inputType']; ?>" class="inputText" name="values[<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>]" value="<?php echo StringUtil::encodeHTML($this->v['optionData']['optionValue']); ?>" />