<?php
/**
* WoltLab Community Framework
* Template: optionTypeRadiobuttons
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'optionTypeRadiobuttons';
?>
<ul class="formOptionsLong">
	<?php
if (count($this->v['options']) > 0) {
foreach ($this->v['options'] as $this->v['key'] => $this->v['option']) {
?>
		<li>
			<label><input <?php if ($this->v['option']['enableOptions']) { ?>onclick="if (IS_SAFARI) <?php echo $this->v['option']['enableOptions']; ?>" onfocus="<?php echo $this->v['option']['enableOptions']; ?>" <?php } ?>
			type="radio" name="values[<?php echo StringUtil::encodeHTML($this->v['optionData']['optionName']); ?>]" value="<?php echo StringUtil::encodeHTML($this->v['key']); ?>"
			<?php if ($this->v['optionData']['optionValue'] == $this->v['key']) { ?>checked="checked" <?php } ?>/>
			<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['option']['value']; ?><?php $_lang6723edef045b3d0c23ad20590bf0096004e2acc8 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang6723edef045b3d0c23ad20590bf0096004e2acc8, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></label>
		</li>
	<?php } } ?>
</ul>