<?php
/**
* WoltLab Community Framework
* Template: messageFormSmileys
* Compiled at: Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'messageFormSmileys';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><div class="hidden" id="smilies">
	<fieldset class="noJavaScript">
		<legend class="noJavaScript">Smileys</legend>
		
		<div id="smileyContainer">
			<ul class="smileys" id="smileyCategory-0"><?php
if (count($this->v['defaultSmileys']) > 0) {
foreach ($this->v['defaultSmileys'] as $this->v['smiley']) {
?><li><img onmouseover="this.style.cursor='pointer'" onclick="WysiwygInsert('smiley', '<?php echo StringUtil::encodeHTML($this->v['smiley']->getURL()); ?>', '<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['smiley']->smileyTitle), $this)); ?><?php $_langcf89adb6f81d3086c2b8a3de3a6cc0d1e9cff24d = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langcf89adb6f81d3086c2b8a3de3a6cc0d1e9cff24d, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>', '<?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['smiley']->smileyCode), $this)); ?>');" src="<?php echo StringUtil::encodeHTML($this->v['smiley']->getURL()); ?>" alt="" title="<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['smiley']->smileyTitle); ?><?php $_lang6ab1dc3515231565147a4f9aa27f37ab53c1683a = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang6ab1dc3515231565147a4f9aa27f37ab53c1683a, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>" /></li><?php } } ?></ul>
		</div>
	</fieldset>
</div>

<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/SmileyCategorySwitcher.class.js"></script>
<script type="text/javascript">
	//<![CDATA[
	tabbedPane.addTab('smilies', false);
	
	// define smiley categories
	var smileyCategories = new Hash();
	smileyCategories.set(0, 'Standard (<?php echo StringUtil::formatNumeric(count($this->v['defaultSmileys'])); ?>)');
	<?php
if (count($this->v['smileyCategories']) > 0) {
foreach ($this->v['smileyCategories'] as $this->v['smileyCategory']) {
?>
		<?php if ( ! $this->v['smileyCategory']->disabled) { ?>smileyCategories.set(<?php echo $this->v['smileyCategory']->smileyCategoryID; ?>, '<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['smileyCategory']->title); ?><?php $_lang6fcada3f26335ee4c38ef404194fe8ad5946eec8 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang6fcada3f26335ee4c38ef404194fe8ad5946eec8, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> (<?php echo StringUtil::formatNumeric($this->v['smileyCategory']->smileys); ?>)');<?php } ?>
	<?php } } ?>
	
	// init smiley category switcher
	var smileyCategorySwitcher = new SmileyCategorySwitcher(smileyCategories);
	<?php if ($this->v['activeTab'] == 'smilies' || $this->v['activeTab'] == '') { ?>
		document.observe("dom:loaded", function() {
			smileyCategorySwitcher.showSmileyCategories();
		});
	<?php } ?>
	//]]>
</script>