<?php
/**
* WoltLab Community Framework
* Template: messageFormTabs
* Compiled at: Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'messageFormTabs';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><input type="submit" name="send" value="Absenden" class="hidden" />
<div class="hidden" id="tabMenu">
	<ul id="tabMenuList">
		<?php if (MODULE_SMILEY && $this->v['showSmilies'] && $this->v['canUseSmilies']) { ?><li id="smiliesTab"><a onclick="tabbedPane.openTab('smilies');"><span>Smileys</span></a></li><?php } ?>
		<?php if ($this->v['showSettings']) { ?><li id="settingsTab"><a onclick="tabbedPane.openTab('settings');"><span>Einstellungen</span></a></li><?php } ?>
		<?php if (MODULE_ATTACHMENT && $this->v['showAttachments']) { ?><li id="attachmentsEditTab"><a onclick="tabbedPane.openTab('attachmentsEdit');"><span>Dateianhänge</span></a></li><?php } ?>
		<?php if (MODULE_POLL && $this->v['showPoll']) { ?><li id="pollEditTab"><a onclick="tabbedPane.openTab('pollEdit');"><span>Umfrage</span></a></li><?php } ?>
		<?php if (isset($this->v['additionalTabs'])) { ?><?php echo $this->v['additionalTabs']; ?><?php } ?>
	</ul>
</div>
<div class="hidden" id="subTabMenu"><div class="containerHead"><div> </div></div></div>
<div id="tabContent">
	<?php if (MODULE_SMILEY && $this->v['showSmilies'] && $this->v['canUseSmilies']) { ?><?php
$outerTemplateName10dc3bd8ddc3f1156545136a6d2f7a07d1c97104 = $this->v['tpl']['template'];
$this->includeTemplate("messageFormSmileys", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName10dc3bd8ddc3f1156545136a6d2f7a07d1c97104;
$this->v['tpl']['includedTemplates']["messageFormSmileys"] = 1;
?><?php } ?>
	<?php if ($this->v['showSettings']) { ?><?php
$outerTemplateName60093961c7ba531422ca040b77bf69834ed9838a = $this->v['tpl']['template'];
$this->includeTemplate("messageFormSettings", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName60093961c7ba531422ca040b77bf69834ed9838a;
$this->v['tpl']['includedTemplates']["messageFormSettings"] = 1;
?><?php } ?>
	<?php if (MODULE_ATTACHMENT && $this->v['showAttachments']) { ?><?php
$outerTemplateName9fc411cdc9a08640c5973abf8784852ca6cabaf3 = $this->v['tpl']['template'];
$this->includeTemplate("attachmentsEdit", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName9fc411cdc9a08640c5973abf8784852ca6cabaf3;
$this->v['tpl']['includedTemplates']["attachmentsEdit"] = 1;
?><?php } ?>
	<?php if (MODULE_POLL && $this->v['showPoll']) { ?><?php
$outerTemplateNameba61c5425535519197263795d782be080b7763bf = $this->v['tpl']['template'];
$this->includeTemplate("pollEdit", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameba61c5425535519197263795d782be080b7763bf;
$this->v['tpl']['includedTemplates']["pollEdit"] = 1;
?><?php } ?>
	<?php if (isset($this->v['additionalSubTabs'])) { ?><?php echo $this->v['additionalSubTabs']; ?><?php } ?>
</div>
<input id="activeTab" type="hidden" name="activeTab" value="<?php echo StringUtil::encodeHTML($this->v['activeTab']); ?>" />
<script type="text/javascript">
	//<![CDATA[
	tabbedPane.init('<?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['activeTab']), $this)); ?>');
	//]]>
</script>