<?php
/**
* WoltLab Community Framework
* Template: signatureEdit
* Compiled at: Sun, 08 Jun 2014 21:37:21 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'signatureEdit';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCounter'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCounter.class.php');
$this->pluginObjects['TemplatePluginFunctionCounter'] = new TemplatePluginFunctionCounter;
}
if (!isset($this->pluginObjects['TemplatePluginModifierFilesize'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierFilesize.class.php');
$this->pluginObjects['TemplatePluginModifierFilesize'] = new TemplatePluginModifierFilesize;
}
?><?php
$outerTemplateNameeafb7fff7104ccbd63f68173e77541b24e0547d3 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameeafb7fff7104ccbd63f68173e77541b24e0547d3;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Signatur bearbeiten - Profil bearbeiten - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langeba29de87d91817103a585b0693b7bf1426f3deb = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langeba29de87d91817103a585b0693b7bf1426f3deb, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	
	<?php
$outerTemplateNamebb57703ad364f6216075ba6e28bc27a00745f16f = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamebb57703ad364f6216075ba6e28bc27a00745f16f;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/TabbedPane.class.js"></script>
	<?php if ($this->v['canUseBBCodes']) { ?><?php
$outerTemplateName8ce8056a1a8f5b54dfa927d8d8872624ed40dc64 = $this->v['tpl']['template'];
$this->includeTemplate("wysiwyg", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName8ce8056a1a8f5b54dfa927d8d8872624ed40dc64;
$this->v['tpl']['includedTemplates']["wysiwyg"] = 1;
?><?php } ?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateName1617d2c2e02b90cae91be4518757e81e493753ff = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName1617d2c2e02b90cae91be4518757e81e493753ff;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<?php ob_start(); ?>
		<?php if ($this->v['errorField']) { ?>
			<p class="error">Ihre Angaben sind ungültig. Bitte überprüfen Sie die markierten Eingabefelder.</p>
		<?php } ?>
		
		<?php if (isset($this->v['success'])) { ?>
			<p class="success">Ihre Signatur wurde erfolgreich gespeichert.</p>
		<?php } ?>
		
		<?php if ($this->v['this']->user->disableSignature) { ?>
			<p class="error"><?php if ($this->v['this']->user->disableSignatureReason) { ?>Ihre Signatur wurde vom Administrator aus folgenden Gründen gesperrt: <?php echo StringUtil::encodeHTML($this->v['this']->user->disableSignatureReason); ?><?php } else { ?>Ihre Signatur wurde vom Administrator gesperrt.<?php } ?></p>
		<?php } ?>
	<?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->append('userMessages', $this->v['tpl']['capture']['default']);
?>
	
	<?php
$outerTemplateName9afe44181a0e385c88e966512d0dfdc3a13df134 = $this->v['tpl']['template'];
$this->includeTemplate("userCPHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName9afe44181a0e385c88e966512d0dfdc3a13df134;
$this->v['tpl']['includedTemplates']["userCPHeader"] = 1;
?>
	
	<form method="post" action="index.php?form=SignatureEdit">
		<div class="border tabMenuContent">
			<div class="container-1">
				<h3 class="subHeadline">Signatur bearbeiten</h3>
					
				<?php if ($this->v['signatureCache']) { ?>
					<fieldset>
						<legend>Bisherige Signatur</legend>
						<div>
							<?php echo $this->v['signatureCache']; ?>
						</div>
					</fieldset>
				<?php } ?>
				
				<?php if ($this->v['signaturePreview']) { ?>
					<fieldset>
						<legend>Neue Signatur</legend>
						<div>
							<?php echo $this->v['signaturePreview']; ?>
						</div>
					</fieldset>
				<?php } ?>
				
				<?php if ( ! $this->v['this']->user->disableSignature) { ?>
					<fieldset>
						<legend>Signatur</legend>
						<div class="editorFrame formElement<?php if ($this->v['errorField'] == 'text') { ?> formError<?php } ?>" id="textDiv">
							<div class="formFieldLabel">
								<label for="text">Signatur</label>
							</div>
							<div class="formField">
								<textarea name="text" id="text" cols="40" rows="15" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>"><?php echo StringUtil::encodeHTML($this->v['text']); ?></textarea>
								<?php if ($this->v['errorField'] == 'text') { ?>
									<p class="innerError">
										<?php if ($this->v['errorType'] == 'tooLong') { ?>Ihre Signatur ist zu lang. Es stehen maximal <?php echo StringUtil::formatNumeric($this->v['maxTextLength']); ?> Zeichen zur Verfügung.<?php } ?>
										<?php if ($this->v['errorType'] == 'tooManyImages') { ?>Ihre Signatur enthält zu viele Bilder. Es <?php if ($this->v['maxImages'] == 1) { ?>ist<?php } else { ?>sind<?php } ?> maximal nur <?php echo StringUtil::formatNumeric($this->v['maxImages']); ?> Bild<?php if ($this->v['maxImages'] != 1) { ?>er<?php } ?> pro Signatur erlaubt.<?php } ?>
										<?php if ($this->v['errorType'] == 'censoredWordsFound') { ?>Ihre Nachricht enthält folgende zensierte Wörter: <?php
$_lengthc81afbbeb58a7189963736fd9631e1b2dd1d1d2e = count($this->v['censoredWords']);
$_ic81afbbeb58a7189963736fd9631e1b2dd1d1d2e = 0;
foreach ($this->v['censoredWords'] as $this->v['censoredWord'] => $this->v['number']) { ?><?php echo StringUtil::encodeHTML($this->v['censoredWord']); ?><?php if ($this->v['number'] > 1) { ?> (<?php echo StringUtil::formatNumeric($this->v['number']); ?>x)<?php } ?><?php
if (++$_ic81afbbeb58a7189963736fd9631e1b2dd1d1d2e < $_lengthc81afbbeb58a7189963736fd9631e1b2dd1d1d2e) { echo ', '; }
} ?><?php } ?>
										<?php if (is_array($this->v['errorType'])) { ?>
											<?php
if (count($this->v['errorType']) > 0) {
foreach ($this->v['errorType'] as $this->v['error']) {
?>
												<?php if ($this->v['error']['errorType'] == 'tooLarge') { ?>Das Bild &raquo;<?php echo StringUtil::encodeHTML($this->v['error']['image']); ?>&laquo; überschreitet die erlaubte Maximalgröße. Die maximale Größe liegt bei <?php echo StringUtil::formatNumeric($this->v['this']->user->getPermission('user.profile.signature.maxImageWidth')); ?>*<?php echo StringUtil::formatNumeric($this->v['this']->user->getPermission('user.profile.signature.maxImageHeight')); ?> Pixel und <?php echo $this->pluginObjects['TemplatePluginModifierFilesize']->execute(array($this->v['this']->user->getPermission('user.profile.signature.maxImageSize')), $this); ?>.<?php } ?>
											<?php } } ?>
										<?php } ?>
									</p>
								<?php } ?>
							</div>
						</div>
						
						<?php
$outerTemplateName4f5d25da98d8933ec195d00862598d602cd0d48f = $this->v['tpl']['template'];
$this->includeTemplate("messageFormTabs", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName4f5d25da98d8933ec195d00862598d602cd0d48f;
$this->v['tpl']['includedTemplates']["messageFormTabs"] = 1;
?>
					</fieldset>
				<?php } ?>
				
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
			</div>
		</div>
		<?php if ( ! $this->v['this']->user->disableSignature) { ?>
			<div class="formSubmit">
				<?php echo SID_INPUT_TAG; ?>
				<input type="submit" accesskey="s" value="Absenden" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
				<input type="submit" name="preview" accesskey="p" value="Vorschau" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
				<input type="reset" name="reset" accesskey="r" value="Zurücksetzen" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
			</div>
		<?php } ?>
	</form>

</div>

<?php
$outerTemplateName011bedbbdefe44467395f70fd038a6f75fada66b = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName011bedbbdefe44467395f70fd038a6f75fada66b;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>