<?php
/**
* WoltLab Community Framework
* Template: usersOnline
* Compiled at: Mon, 09 Jun 2014 00:58:19 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'usersOnline';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginModifierShorttime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierShorttime.class.php');
$this->pluginObjects['TemplatePluginModifierShorttime'] = new TemplatePluginModifierShorttime;
}
?><?php
$outerTemplateName69f962c24bb01a1276fa411cacb0e21e0e9218b9 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName69f962c24bb01a1276fa411cacb0e21e0e9218b9;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>&raquo;Wer ist online?&laquo;-Liste - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langd5b2b3bff58048e854b8127c7778b394a6e3cf35 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langd5b2b3bff58048e854b8127c7778b394a6e3cf35, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateNamec193f0393dc9b8eb638f96831222cc5049ca3f0e = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamec193f0393dc9b8eb638f96831222cc5049ca3f0e;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<?php if (USERS_ONLINE_PAGE_REFRESH > 0) { ?>
		<meta http-equiv="refresh" content="<?php echo USERS_ONLINE_PAGE_REFRESH; ?>; url=index.php?page=UsersOnline&amp;sortField=<?php echo StringUtil::encodeHTML($this->v['sortField']); ?>&amp;sortOrder=<?php echo StringUtil::encodeHTML($this->v['sortOrder']); ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>" />
	<?php } ?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateNamef0858a30e0abc81d7464ee92c20951ca4eda5dc7 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamef0858a30e0abc81d7464ee92c20951ca4eda5dc7;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<ul class="breadCrumbs">
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang12c20c9def5803697e5d4d3bfd3d2f2aa55ad4cc = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang12c20c9def5803697e5d4d3bfd3d2f2aa55ad4cc, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	</ul>
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('membersL.png'); ?>" alt="" /> 
		<div class="headlineContainer">
			<h2>&raquo;Wer ist online?&laquo;-Liste</h2>
			<?php if (count($this->v['users']) > 0 && count($this->v['usersOnlineMarkings']) > 0) { ?>
				<p class="smallFont">
				Legende: <?php
$_length90bbd313efd544fbefd9685c382226ef25a0a0b9 = count($this->v['usersOnlineMarkings']);
$_i90bbd313efd544fbefd9685c382226ef25a0a0b9 = 0;
foreach ($this->v['usersOnlineMarkings'] as $this->v['usersOnlineMarking']) { ?><?php echo $this->v['usersOnlineMarking']; ?><?php
if (++$_i90bbd313efd544fbefd9685c382226ef25a0a0b9 < $_length90bbd313efd544fbefd9685c382226ef25a0a0b9) { echo ', '; }
} ?>
				</p>
			<?php } ?>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<div class="userOnline">
		<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2', 'print' => false, 'advance' => false), $this); ?>
		<?php if (count($this->v['users']) > 0) { ?>
			<div class="border titleBarPanel">
				<div class="containerHead"><h3>Es <?php if (count($this->v['users']) == 1) { ?>ist ein Mitglied<?php } else { ?>sind <?php echo StringUtil::formatNumeric(count($this->v['users'])); ?> Mitglieder<?php } ?> online</h3></div>
			</div>
			<div class="border borderMarginRemove">
				<table class="tableList">
					<thead>
						<tr class="tableHead">
							<th class="columnUsername<?php if ($this->v['sortField'] == 'username') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=username&amp;sortOrder=<?php if ($this->v['sortField'] == 'username' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Benutzername
									<?php if ($this->v['sortField'] == 'username') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_iconb136dae16eac0710eb0ec1453ebb43d7e1ed4639 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconb136dae16eac0710eb0ec1453ebb43d7e1ed4639); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							<?php if ($this->v['canViewIpAddress']) { ?>
								<th class="columnIP<?php if ($this->v['sortField'] == 'ipAddress') { ?> active<?php } ?>">
									<div><a href="index.php?page=UsersOnline&amp;sortField=ipAddress&amp;sortOrder=<?php if ($this->v['sortField'] == 'ipAddress' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
										IP-Adresse
										<?php if ($this->v['sortField'] == 'ipAddress') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon5864d2b8ac09c229a50355b96b2f259043fcb50c = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon5864d2b8ac09c229a50355b96b2f259043fcb50c); ?>" alt="" /><?php } ?>
									</a></div>
								</th>
								<th class="columnUserAgent<?php if ($this->v['sortField'] == 'userAgent') { ?> active<?php } ?>">
									<div><a href="index.php?page=UsersOnline&amp;sortField=userAgent&amp;sortOrder=<?php if ($this->v['sortField'] == 'userAgent' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
										Browser-Kennung
										<?php if ($this->v['sortField'] == 'userAgent') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_iconcfa26ab318f1b1c903549b7d4e1d5e17065ed05d = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconcfa26ab318f1b1c903549b7d4e1d5e17065ed05d); ?>" alt="" /><?php } ?>
									</a></div>
								</th>
							<?php } ?>
							<th class="columnLastActivity<?php if ($this->v['sortField'] == 'lastActivityTime') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=lastActivityTime&amp;sortOrder=<?php if ($this->v['sortField'] == 'lastActivityTime' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Letzte Aktion
									<?php if ($this->v['sortField'] == 'lastActivityTime') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_iconad92b8a01198b32a3144678b3feeada08f31239a = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconad92b8a01198b32a3144678b3feeada08f31239a); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							<th class="columnLocation<?php if ($this->v['sortField'] == 'requestURI') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=requestURI&amp;sortOrder=<?php if ($this->v['sortField'] == 'requestURI' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Ort
									<?php if ($this->v['sortField'] == 'requestURI') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icond48cbd43aa644822501995bb02eed13b0f3e1f55 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icond48cbd43aa644822501995bb02eed13b0f3e1f55); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							
							<?php if (isset($this->v['additionalColumns'])) { ?><?php echo $this->v['additionalColumns']; ?><?php } ?>
						</tr>
					</thead>
					<tbody>
						<?php
if (count($this->v['users']) > 0) {
foreach ($this->v['users'] as $this->v['user']) {
?>
							<tr class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?>">
								<td class="columnUsername" style="width: 20%"><p><a href="index.php?page=User&amp;userID=<?php echo $this->v['user']['userID']; ?><?php echo SID_ARG_2ND; ?>"><?php echo $this->v['user']['username']; ?></a></p></td>
								<?php if ($this->v['canViewIpAddress']) { ?>
									<td class="columnIP"><p><?php echo StringUtil::encodeHTML($this->v['user']['ipAddress']); ?></p></td>
									<td class="columnUserAgent" style="width: 30%">
										<div class="containerIcon">
											<?php if ($this->v['user']['userAgentIcon']) { ?><img src="<?php ob_start(); ?>browsers/<?php echo $this->v['user']['userAgentIcon']; ?>M.png<?php $_icon19da8168d6a2fcf2bc71e93407b3b46b98f3db07 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon19da8168d6a2fcf2bc71e93407b3b46b98f3db07); ?>" alt="" /><?php } ?>
										</div>
										<div class="containerContent">
											<p><?php echo StringUtil::encodeHTML($this->v['user']['userAgent']); ?></p>
										</div>
									</td>
								<?php } ?>
								<td class="columnLastActivity"><p><?php echo $this->pluginObjects['TemplatePluginModifierShorttime']->execute(array($this->v['user']['lastActivityTime']), $this); ?></p></td>
								<td class="columnLocation" style="width: <?php if ($this->v['canViewIpAddress']) { ?>50<?php } else { ?>80<?php } ?>%;"><p><?php echo $this->v['user']['location']; ?></p></td>
								
								<?php if (isset($this->v['user']['additionalColumns'])) { ?><?php echo $this->v['user']['additionalColumns']; ?><?php } ?>
							</tr>
						<?php } } ?>
					</tbody>
				</table>
			</div>
		<?php } ?>
		
		<?php if (count($this->v['guests']) > 0) { ?>
			<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('reset' => true, 'advance' => false, 'print' => false), $this); ?>
			<div class="border titleBarPanel">
				<div class="containerHead"><h3>Es <?php if (count($this->v['guests']) == 1) { ?>ist ein Gast<?php } else { ?>sind <?php echo StringUtil::formatNumeric(count($this->v['guests'])); ?> Gäste<?php } ?> online</h3></div>
			</div>
			<div class="border borderMarginRemove">
				<table class="tableList">
					<thead>
						<tr class="tableHead">
							<th class="columnUsername<?php if ($this->v['sortField'] == 'username') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=username&amp;sortOrder=<?php if ($this->v['sortField'] == 'username' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Name
									<?php if ($this->v['sortField'] == 'username') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon4d913022dbd8544fd2b26931e67dc29f2f22edda = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon4d913022dbd8544fd2b26931e67dc29f2f22edda); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							<?php if ($this->v['canViewIpAddress']) { ?>
								<th class="columnIP<?php if ($this->v['sortField'] == 'ipAddress') { ?> active<?php } ?>">
									<div><a href="index.php?page=UsersOnline&amp;sortField=ipAddress&amp;sortOrder=<?php if ($this->v['sortField'] == 'ipAddress' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
										IP-Adresse
										<?php if ($this->v['sortField'] == 'ipAddress') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon430aae96c1ef9b321e004ab1dd4a5ec2b7941175 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon430aae96c1ef9b321e004ab1dd4a5ec2b7941175); ?>" alt="" /><?php } ?>
									</a></div>
								</th>
								<th class="columnUserAgent<?php if ($this->v['sortField'] == 'userAgent') { ?> active<?php } ?>">
									<div><a href="index.php?page=UsersOnline&amp;sortField=userAgent&amp;sortOrder=<?php if ($this->v['sortField'] == 'userAgent' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
										Browser-Kennung
										<?php if ($this->v['sortField'] == 'userAgent') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon3d726fbf6808570a8f4f19bcc4270baea625ffdd = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon3d726fbf6808570a8f4f19bcc4270baea625ffdd); ?>" alt="" /><?php } ?>
									</a></div>
								</th>
							<?php } ?>
							<th class="columnLastActivity<?php if ($this->v['sortField'] == 'lastActivityTime') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=lastActivityTime&amp;sortOrder=<?php if ($this->v['sortField'] == 'lastActivityTime' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Letzte Aktion
									<?php if ($this->v['sortField'] == 'lastActivityTime') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon45b3492f1569e739c505d63067db4dc6ac456cfe = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon45b3492f1569e739c505d63067db4dc6ac456cfe); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							<th class="columnLocation<?php if ($this->v['sortField'] == 'requestURI') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=requestURI&amp;sortOrder=<?php if ($this->v['sortField'] == 'requestURI' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Ort
									<?php if ($this->v['sortField'] == 'requestURI') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon30d0afecf6a9eb25e97f7ba57af55c7d0ed86e63 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon30d0afecf6a9eb25e97f7ba57af55c7d0ed86e63); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							
							<?php if (isset($this->v['additionalColumns'])) { ?><?php echo $this->v['additionalColumns']; ?><?php } ?>
						</tr>
					</thead>
					<tbody>
						<?php
if (count($this->v['guests']) > 0) {
foreach ($this->v['guests'] as $this->v['guest']) {
?>
							<tr class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?>">
								<td class="columnUsername" style="width: 20%"><p><?php echo StringUtil::encodeHTML($this->v['guest']['guestname']); ?></p></td>
								<?php if ($this->v['canViewIpAddress']) { ?>
									<td class="columnIP"><p><?php echo StringUtil::encodeHTML($this->v['guest']['ipAddress']); ?></p></td>
									<td class="columnUserAgent" style="width: 30%">
										<div class="containerIcon">
											<?php if ($this->v['guest']['userAgentIcon']) { ?><img src="<?php ob_start(); ?>browsers/<?php echo $this->v['guest']['userAgentIcon']; ?>M.png<?php $_icone7aad4144ae4729fd87986a1178236b0e34984cd = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icone7aad4144ae4729fd87986a1178236b0e34984cd); ?>" alt="" /><?php } ?>
										</div>
										<div class="containerContent">
											<p><?php echo StringUtil::encodeHTML($this->v['guest']['userAgent']); ?></p>
										</div>
									</td>
								<?php } ?>
								<td class="columnLastActivity"><p><?php echo $this->pluginObjects['TemplatePluginModifierShorttime']->execute(array($this->v['guest']['lastActivityTime']), $this); ?></p></td>
								<td class="columnLocation" style="width: <?php if ($this->v['canViewIpAddress']) { ?>50<?php } else { ?>80<?php } ?>%"><p><?php echo $this->v['guest']['location']; ?></p></td>
								
								<?php if (isset($this->v['guest']['additionalColumns'])) { ?><?php echo $this->v['guest']['additionalColumns']; ?><?php } ?>
							</tr>
						<?php } } ?>
					</tbody>
				</table>
			</div>
		<?php } ?>
		
		<?php if (count($this->v['spiders']) > 0) { ?>
			<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('reset' => true, 'advance' => false, 'print' => false), $this); ?>
			<div class="border titleBarPanel">
				<div class="containerHead"><h3>Es <?php if (count($this->v['spiders']) == 1) { ?>ist ein Suchmaschinenroboter<?php } else { ?>sind <?php echo StringUtil::formatNumeric(count($this->v['spiders'])); ?> Suchmaschinenroboter<?php } ?> online
(<?php if ($this->v['detailedSpiderList']) { ?><a href="index.php?page=UsersOnline&amp;sortField=<?php echo StringUtil::encodeHTML($this->v['sortField']); ?>&amp;sortOrder=<?php echo StringUtil::encodeHTML($this->v['sortOrder']); ?>&amp;detailedSpiderList=0<?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">Details aus</a><?php } else { ?><a href="index.php?page=UsersOnline&amp;sortField=<?php echo StringUtil::encodeHTML($this->v['sortField']); ?>&amp;sortOrder=<?php echo StringUtil::encodeHTML($this->v['sortOrder']); ?>&amp;detailedSpiderList=1<?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">Details an</a><?php } ?>)</h3></div>
			</div>
			<div class="border borderMarginRemove">
				<table class="tableList">
					<thead>
						<tr class="tableHead">
							<th class="columnUsername<?php if ($this->v['sortField'] == 'username') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=username&amp;sortOrder=<?php if ($this->v['sortField'] == 'username' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Name
									<?php if ($this->v['sortField'] == 'username') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon79ceb885537deed8741525427d30bc275975e924 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon79ceb885537deed8741525427d30bc275975e924); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							<?php if ($this->v['canViewIpAddress']) { ?>
								<th class="columnLastActivity<?php if ($this->v['sortField'] == 'ipAddress') { ?> active<?php } ?>">
									<div><a href="index.php?page=UsersOnline&amp;sortField=ipAddress&amp;sortOrder=<?php if ($this->v['sortField'] == 'ipAddress' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
										IP-Adresse
										<?php if ($this->v['sortField'] == 'ipAddress') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_iconf4abf5fdbfbecd325e14a7542d85994e51e69ad8 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconf4abf5fdbfbecd325e14a7542d85994e51e69ad8); ?>" alt="" /><?php } ?>
									</a></div>
								</th>
								<th class="columnUserAgent<?php if ($this->v['sortField'] == 'userAgent') { ?> active<?php } ?>">
									<div><a href="index.php?page=UsersOnline&amp;sortField=userAgent&amp;sortOrder=<?php if ($this->v['sortField'] == 'userAgent' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
										Browser-Kennung
										<?php if ($this->v['sortField'] == 'userAgent') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon536e2da75cbe5581f2cc1d0087e38edac28526a9 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon536e2da75cbe5581f2cc1d0087e38edac28526a9); ?>" alt="" /><?php } ?>
									</a></div>
								</th>
							<?php } ?>
							<th class="columnLastActivity<?php if ($this->v['sortField'] == 'lastActivityTime') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=lastActivityTime&amp;sortOrder=<?php if ($this->v['sortField'] == 'lastActivityTime' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Letzte Aktion
									<?php if ($this->v['sortField'] == 'lastActivityTime') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon45c528abaa9954b2d0818883efc35c3abd92753c = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon45c528abaa9954b2d0818883efc35c3abd92753c); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							<th class="columnLocation<?php if ($this->v['sortField'] == 'requestURI') { ?> active<?php } ?>">
								<div><a href="index.php?page=UsersOnline&amp;sortField=requestURI&amp;sortOrder=<?php if ($this->v['sortField'] == 'requestURI' && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?>&amp;detailedSpiderList=<?php echo $this->v['detailedSpiderList']; ?><?php if (isset($this->v['additionalParameters'])) { ?><?php echo $this->v['additionalParameters']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">
									Ort
									<?php if ($this->v['sortField'] == 'requestURI') { ?><img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_icon148e9bf4c300999a08b62ebcb8335ce0f625a6d3 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon148e9bf4c300999a08b62ebcb8335ce0f625a6d3); ?>" alt="" /><?php } ?>
								</a></div>
							</th>
							
							<?php if (isset($this->v['additionalColumns'])) { ?><?php echo $this->v['additionalColumns']; ?><?php } ?>
						</tr>
					</thead>
					<tbody>
						<?php
if (count($this->v['spiders']) > 0) {
foreach ($this->v['spiders'] as $this->v['spider']) {
?>
							<tr class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?>">
								<td class="columnUsername" style="width: 20%"><p><?php if ($this->v['spider']['spiderURL']) { ?><a href="<?php echo StringUtil::encodeHTML($this->v['spider']['spiderURL']); ?>"><?php echo StringUtil::encodeHTML($this->v['spider']['spiderName']); ?></a><?php } else { ?><?php echo StringUtil::encodeHTML($this->v['spider']['spiderName']); ?><?php } ?><?php if ($this->v['spider']['count'] > 1) { ?> (<?php echo StringUtil::formatNumeric($this->v['spider']['count']); ?>x)<?php } ?></p></td>
								<?php if ($this->v['canViewIpAddress']) { ?>
									<td class="columnIP"><p><?php echo StringUtil::encodeHTML($this->v['spider']['ipAddress']); ?></p></td>
									<td class="columnUserAgent" style="width: 30%">
										<div class="containerIcon">
											<?php if ($this->v['spider']['userAgentIcon']) { ?><img src="<?php ob_start(); ?>browsers/<?php echo $this->v['spider']['userAgentIcon']; ?>M.png<?php $_icon51287d9a266d61f382596c913f17452db54ff9e0 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon51287d9a266d61f382596c913f17452db54ff9e0); ?>" alt="" /><?php } ?>
										</div>
										<div class="containerContent">
											<p><?php echo StringUtil::encodeHTML($this->v['spider']['userAgent']); ?></p>
										</div>
									</td>
								<?php } ?>
								<td class="columnLastActivity"><p><?php echo $this->pluginObjects['TemplatePluginModifierShorttime']->execute(array($this->v['spider']['lastActivityTime']), $this); ?></p></td>
								<td class="columnLocation" style="width: <?php if ($this->v['canViewIpAddress']) { ?>50<?php } else { ?>80<?php } ?>%"><p><?php echo $this->v['spider']['location']; ?></p></td>
								
								<?php if (isset($this->v['spider']['additionalColumns'])) { ?><?php echo $this->v['spider']['additionalColumns']; ?><?php } ?>
							</tr>
						<?php } } ?>
					</tbody>
				</table>
			</div>
		<?php } ?>
	</div>

</div>

<?php
$outerTemplateNamed13c91aff09f03df6ce12f14bfa23248803667ef = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamed13c91aff09f03df6ce12f14bfa23248803667ef;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>