<?php
/**
* WoltLab Community Framework
* Template: userProfileEditOnlineMarkingSelect
* Compiled at: Sun, 08 Jun 2014 21:37:10 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userProfileEditOnlineMarkingSelect';
?>
<ul class="formOptionsLong">
	<?php
if (count($this->v['markings']) > 0) {
foreach ($this->v['markings'] as $this->v['marking']) {
?>
		<li><label><input type="radio" name="userOnlineGroupID" value="<?php echo $this->v['marking']['groupID']; ?>" <?php if ($this->v['marking']['groupID'] == $this->v['userOnlineGroupID']) { ?>checked="checked" <?php } ?>/> <?php echo $this->v['marking']['userOnlineMarking']; ?> <span class="smallFont light">(<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['marking']['groupName']); ?><?php $_lange7000c215134f7e52ff8e319dfe2e319fdd3ddeb = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lange7000c215134f7e52ff8e319dfe2e319fdd3ddeb, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>)</span></label></li>
	<?php } } ?>
</ul>