<?php
/**
* WoltLab Community Framework
* Template: thread
* Compiled at: Wed, 28 May 2014 19:47:36 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'thread';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierConcat'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierConcat.class.php');
$this->pluginObjects['TemplatePluginModifierConcat'] = new TemplatePluginModifierConcat;
}
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionPages'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionPages.class.php');
$this->pluginObjects['TemplatePluginFunctionPages'] = new TemplatePluginFunctionPages;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginModifierTime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierTime.class.php');
$this->pluginObjects['TemplatePluginModifierTime'] = new TemplatePluginModifierTime;
}
if (!isset($this->pluginObjects['TemplatePluginModifierShorttime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierShorttime.class.php');
$this->pluginObjects['TemplatePluginModifierShorttime'] = new TemplatePluginModifierShorttime;
}
if (!isset($this->pluginObjects['TemplatePluginModifierDatediff'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierDatediff.class.php');
$this->pluginObjects['TemplatePluginModifierDatediff'] = new TemplatePluginModifierDatediff;
}
?><?php
$outerTemplateNamef9e8e7bf008141d1a5c1e8e3d9f11fff96b9c621 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamef9e8e7bf008141d1a5c1e8e3d9f11fff96b9c621;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title><?php if ($this->v['thread']->prefix) { ?><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['thread']->prefix); ?><?php $_lang57c049ea0b96e9a1e5c1dbd829beea9fcd8944cb = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang57c049ea0b96e9a1e5c1dbd829beea9fcd8944cb, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> <?php } ?><?php echo StringUtil::encodeHTML($this->v['thread']->topic); ?> <?php if ($this->v['pageNo'] > 1) { ?>- Seite <?php echo StringUtil::formatNumeric($this->v['pageNo']); ?> <?php } ?> - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['board']->title); ?><?php $_lang18c32fb00aba980b16142810d29d8846a2e7b9ea = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang18c32fb00aba980b16142810d29d8846a2e7b9ea, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langf193a7bcfacde340d3c477bcb57535477841fa33 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langf193a7bcfacde340d3c477bcb57535477841fa33, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	
	<?php
$outerTemplateNamea5497f9bfd4419c40351a417337f0e1c6bb9c9dc = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamea5497f9bfd4419c40351a417337f0e1c6bb9c9dc;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	
	<?php
$outerTemplateName1b4e205ec550b25bc73e06dc02c9ca864ddc833b = $this->v['tpl']['template'];
$this->includeTemplate('imageViewer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName1b4e205ec550b25bc73e06dc02c9ca864ddc833b;
$this->v['tpl']['includedTemplates']['imageViewer'] = 1;
?>
	
	<!--[if IE]>
		<script type="text/javascript">
			//<![CDATA[
			
			onloadEvents.push(function() {
				if (document.referrer) {
					var postForm = document.referrer.search(/PostEdit|PostAdd/);
					if (postForm != -1) {
						var postID = (window.location + '').split('postID=');
						if (!isNaN(postID[1])) window.location.href = '#post' + postID[1];
					}
				}
				});
			
			//]]>
		</script>
	<![endif]-->
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/MultiPagesLinks.class.js"></script>
	<script type="text/javascript">
		//<![CDATA[
		var INLINE_IMAGE_MAX_WIDTH = <?php echo INLINE_IMAGE_MAX_WIDTH; ?>;
		//]]>
	</script>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/ImageResizer.class.js"></script>
	<?php if (isset($this->v['polls'])) { ?><script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/Poll.class.js"></script><?php } ?>
	<script type="text/javascript">
		//<![CDATA[
		var language = new Object();
		var postData = new Hash();
		var url = 'index.php?page=Thread&threadID=<?php echo $this->v['thread']->threadID; ?>&pageNo=<?php echo $this->v['pageNo']; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>';
		//]]>
	</script>
	<?php if ($this->v['thread']->canReplyThread()) { ?>
		<?php
$outerTemplateNameb853873dbac8690b4a33dc8922533555a53099cd = $this->v['tpl']['template'];
$this->includeTemplate('multiQuote', array('formURL' => $this->pluginObjects['TemplatePluginModifierConcat']->execute(array("index.php?form=PostAdd&threadID={$this->v['threadID']}",SID_ARG_2ND_NOT_ENCODED), $this)), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameb853873dbac8690b4a33dc8922533555a53099cd;
$this->v['tpl']['includedTemplates']['multiQuote'] = 1;
?>
	<?php } else { ?>
		<?php
$outerTemplateName6cd802291bda407f8f0ee683508fb52e670940c5 = $this->v['tpl']['template'];
$this->includeTemplate('multiQuote', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName6cd802291bda407f8f0ee683508fb52e670940c5;
$this->v['tpl']['includedTemplates']['multiQuote'] = 1;
?>
	<?php } ?>
	<?php if ($this->v['permissions']['canHandleThread'] || $this->v['permissions']['canHandlePost']) { ?>
		<?php
$outerTemplateName07853d86dd9bec5024e784f24f00d0bbc24867b1 = $this->v['tpl']['template'];
$this->includeTemplate('threadInlineEdit', array('pageType' => 'thread'), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName07853d86dd9bec5024e784f24f00d0bbc24867b1;
$this->v['tpl']['includedTemplates']['threadInlineEdit'] = 1;
?>
		<script type="text/javascript">
			//<![CDATA[
			threadData.set(<?php echo $this->v['thread']->threadID; ?>, {
				'isMarked': <?php echo $this->v['thread']->isMarked(); ?>,
				'isDeleted': <?php echo $this->v['thread']->isDeleted; ?>,
				'isDisabled': <?php echo $this->v['thread']->isDisabled; ?>,
				'isClosed': <?php echo $this->v['thread']->isClosed; ?>,
				'isSticky': <?php echo $this->v['thread']->isSticky; ?>,
				'isAnnouncement': <?php echo $this->v['thread']->isAnnouncement; ?>,
				'isMoved': 0,
				'prefix': '<?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['thread']->prefix), $this)); ?>',
				'isDone': <?php echo $this->v['thread']->isDone; ?>
			});
			//]]>
		</script>
	<?php } ?>
	<link rel="alternate" type="application/rss+xml" href="index.php?page=PostsFeed&amp;format=rss2&amp;threadID=<?php echo $this->v['threadID']; ?>" title="Beiträge dieses Themas abonnieren (RSS2)" />
	<link rel="alternate" type="application/atom+xml" href="index.php?page=PostsFeed&amp;format=atom&amp;threadID=<?php echo $this->v['threadID']; ?>" title="Beiträge dieses Themas abonnieren (Atom)" />
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>

<p class="skipHeader hidden"><a href="#skipToContent" title="Zum Seiteninhalt springen">Zum Seiteninhalt springen</a></p><!-- support for disabled surfers -->


<?php $this->assign('searchFieldTitle', 'Thema durchsuchen'); ?>
<?php ob_start(); ?>
	<input type="hidden" name="threadID" value="<?php echo $this->v['threadID']; ?>" />
	<input type="hidden" name="types[]" value="post" />
	<input type="hidden" name="findThreads" value="0" />
<?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->assign('searchHiddenFields', $this->v['tpl']['capture']['default']);
?>

<?php
$outerTemplateName4010a4b060ce10a3c02e87240971dc44960dbfea = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName4010a4b060ce10a3c02e87240971dc44960dbfea;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<?php
$outerTemplateName8cbc988a1279fc2d25ffa61eb0cbb8abc9cda7be = $this->v['tpl']['template'];
$this->includeTemplate("navigation", array('showBoard' => true), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName8cbc988a1279fc2d25ffa61eb0cbb8abc9cda7be;
$this->v['tpl']['includedTemplates']["navigation"] = 1;
?>
	
	<a href="#" id="skipToContent"></a><!-- support for disabled surfers -->
	
	<div class="mainHeadline">
		<img id="threadEdit<?php echo $this->v['thread']->threadID; ?>" src="<?php ob_start(); ?><?php echo $this->v['thread']->getIconName(); ?>L.png<?php $_icond47344187facf26ad309373e78b510245d477040 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icond47344187facf26ad309373e78b510245d477040); ?>" alt="" />
		<div class="headlineContainer">
			<h2 id="threadTitle<?php echo $this->v['thread']->threadID; ?>">
				<span id="threadPrefix<?php echo $this->v['thread']->threadID; ?>" class="prefix"><strong><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['thread']->prefix); ?><?php $_langee48c937cc0e4ab67fe8534135da22008ff97b8e = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langee48c937cc0e4ab67fe8534135da22008ff97b8e, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></strong></span>
				<a href="index.php?page=Thread&amp;threadID=<?php echo $this->v['thread']->threadID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['thread']->topic); ?></a>
			</h2>
			<p><?php if ($this->v['enableRating']) { ?><?php echo $this->v['thread']->getRatingOutput(); ?><?php } ?></p>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<div class="contentHeader">
		<?php $this->assign('multiplePagesLink', "index.php?page=Thread&threadID={$this->v['threadID']}&pageNo=%d"); ?>
		<?php if ($this->v['highlight']) { ?>
			<?php $this->assign('encodedHighlight', urlencode($this->v['highlight'])); ?>
			<?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&highlight=',$this->v['encodedHighlight']), $this)); ?>
		<?php } ?>
		<?php echo $this->pluginObjects['TemplatePluginFunctionPages']->execute(array('print' => true, 'assign' => 'pagesOutput', 'link' => $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],SID_ARG_2ND_NOT_ENCODED), $this)), $this); ?>
		<div class="largeButtons">
			<?php if ($this->v['thread']->canReplyThread() || isset($this->v['additionalLargeButtons'])) { ?>
				<ul>
					<?php if ($this->v['thread']->canReplyThread()) { ?><li><a href="index.php?form=PostAdd&amp;threadID=<?php echo $this->v['thread']->threadID; ?><?php echo SID_ARG_2ND; ?>" id="replyButton1" title="Antworten"><img src="<?php echo StyleManager::getStyle()->getIconPath('messageAddM.png'); ?>" alt="" /> <span>Antworten</span></a></li><?php } ?>
					
					<?php if (isset($this->v['additionalLargeButtons'])) { ?><?php echo $this->v['additionalLargeButtons']; ?><?php } ?>
				</ul>
			<?php } ?>
		</div>
	</div>
	
	
	<?php if ($this->v['this']->getStyle()->getVariable('messages.color.cycle')) { ?>
		<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'messageCycle', 'values' => '2,1', 'print' => false), $this); ?>
	<?php } else { ?>
		<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'messageCycle', 'values' => '1', 'print' => false), $this); ?>
	<?php } ?>

	<?php if ($this->v['this']->getStyle()->getVariable('messages.sidebar.color.cycle')) { ?>
		<?php if ($this->v['this']->getStyle()->getVariable('messages.color.cycle')) { ?>
			<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'postCycle', 'values' => '1,2', 'print' => false), $this); ?>
		<?php } else { ?>
			<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'postCycle', 'values' => '3,2', 'print' => false), $this); ?>
		<?php } ?>
	<?php } else { ?>
		<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'postCycle', 'values' => '3', 'print' => false), $this); ?>
	<?php } ?>
	
	<?php ob_start(); ?>message<?php if ($this->v['this']->getStyle()->getVariable('messages.framed')) { ?>Framed<?php } ?><?php echo ucfirst($this->v['this']->getStyle()->getVariable('messages.sidebar.alignment')); ?><?php if ($this->v['this']->getStyle()->getVariable('messages.sidebar.divider.use')) { ?> dividers<?php } ?><?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->assign('messageClass', $this->v['tpl']['capture']['default']);
?>
	<?php ob_start(); ?>messageFooter<?php echo ucfirst($this->v['this']->getStyle()->getVariable('messages.footer.alignment')); ?><?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->assign('messageFooterClass', $this->v['tpl']['capture']['default']);
?>
	
	<?php if ($this->v['sortOrder'] == 'DESC') { ?><?php $this->assign('startIndex', $this->v['items']-$this->v['startIndex']+1); ?><?php } ?>
	<?php
if (count($this->v['posts']) > 0) {
foreach ($this->v['posts'] as $this->v['post']) {
?>
		<?php $this->assign("sidebar", $this->v['sidebarFactory']->get('post',$this->v['post']->postID)); ?>
		<?php $this->assign("author", $this->v['sidebar']->getUser()); ?>
		<?php $this->assign("pollID", $this->v['post']->pollID); ?>
		<?php $this->assign("messageID", $this->v['post']->postID); ?>
		
		<script type="text/javascript">
			//<![CDATA[
				
				quoteData.set('post-<?php echo $this->v['post']->postID; ?>', {
					objectID: <?php echo $this->v['post']->postID; ?>,
					objectType: 'post',
					quotes: <?php echo $this->v['post']->isQuoted(); ?>
				});
				
			<?php if ($this->v['permissions']['canHandleThread'] || $this->v['permissions']['canHandlePost']) { ?>
				postData.set(<?php echo $this->v['post']->postID; ?>, {
					'isMarked': <?php echo $this->v['post']->isMarked(); ?>,
					'isDeleted': <?php echo $this->v['post']->isDeleted; ?>,
					'isDisabled': <?php echo $this->v['post']->isDisabled; ?>,
					'isClosed': <?php echo $this->v['post']->isClosed; ?>
				});
			<?php } ?>
			//]]>
		</script>
		
		<?php $this->assign("hiddenDeletedPost", false); ?>
		<?php $this->assign("hiddenIgnoredPost", false); ?>
		<?php if ($this->v['post']->isDeleted &&  ! $this->v['thread']->isDeleted) { ?>
			<?php $this->assign("hiddenDeletedPost", true); ?>
		<?php } ?>
		<?php if ($this->v['sidebar']->getUser()->userID && $this->v['this']->user->userID && $this->v['this']->user->ignores($this->v['sidebar']->getUser()->userID)) { ?>
			<?php $this->assign("hiddenIgnoredPost", true); ?>
		<?php } ?>
		
		<?php if ( ! $this->v['post']->isDeleted || $this->v['board']->getModeratorPermission('canReadDeletedPost')) { ?>
			<div id="postRow<?php echo $this->v['post']->postID; ?>" class="message<?php if (THREAD_ENABLE_THREAD_AUTHOR && $this->v['sidebar']->getUser()->userID && $this->v['sidebar']->getUser()->userID == $this->v['thread']->userID) { ?> threadStarterPost<?php } ?>"<?php if ($this->v['hiddenDeletedPost'] || $this->v['hiddenIgnoredPost']) { ?> style="display: none"<?php } ?>>
				<div class="messageInner <?php echo $this->v['messageClass']; ?> container-<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'postCycle'), $this); ?><?php if ( ! $this->v['sidebar']->getUser()->userID) { ?> guestPost<?php } ?>">
					<?php if ( ! $this->v['hiddenDeletedPost'] &&  ! $this->v['hiddenIgnoredPost']) { ?><a id="post<?php echo $this->v['post']->postID; ?>"></a><?php } ?>
					
					<?php
$outerTemplateNameed7c403ecfbe41e94adc08171676c9bc1d5ea18d = $this->v['tpl']['template'];
$this->includeTemplate('messageSidebar', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameed7c403ecfbe41e94adc08171676c9bc1d5ea18d;
$this->v['tpl']['includedTemplates']['messageSidebar'] = 1;
?>
					
					<div class="messageContent">
						<div class="messageContentInner color-<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'messageCycle'), $this); ?>">
							<div class="messageHeader">
								<p class="messageCount">
									<a href="index.php?page=Thread&amp;postID=<?php echo $this->v['post']->postID; ?>#post<?php echo $this->v['post']->postID; ?>" title="Permalink zum <?php echo StringUtil::formatNumeric($this->v['startIndex']); ?>. Beitrag" class="messageNumber"><?php echo StringUtil::formatNumeric($this->v['startIndex']); ?></a>
									<?php if ($this->v['permissions']['canMarkPost']) { ?>
										<span class="messageMarkCheckBox">
											<input id="postMark<?php echo $this->v['post']->postID; ?>" type="checkbox" title="Beitrag markieren" />
										</span>
									<?php } ?>
								</p>
								<div class="containerIcon">
									<img id="postEdit<?php echo $this->v['post']->postID; ?>" src="<?php ob_start(); ?><?php echo $this->v['post']->getIconName(); ?>M.png<?php $_icon57cb3bd46ce13aa8e68410b5d6a26f454389b3aa = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon57cb3bd46ce13aa8e68410b5d6a26f454389b3aa); ?>" alt="" />
								</div>
								<div class="containerContent">
									<p class="smallFont light"><?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['post']->time), $this); ?></p>
								</div>
							</div>
							
							<h3 id="postTopic<?php echo $this->v['post']->postID; ?>" class="messageTitle"><span><?php echo StringUtil::encodeHTML($this->v['post']->subject); ?></span></h3>
							
							<div class="messageBody">
								<?php
$outerTemplateName3d81f52cd3bb995bacaea896c9cb698e0eeb7683 = $this->v['tpl']['template'];
$this->includeTemplate('pollShow', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName3d81f52cd3bb995bacaea896c9cb698e0eeb7683;
$this->v['tpl']['includedTemplates']['pollShow'] = 1;
?>
								<div id="postText<?php echo $this->v['post']->postID; ?>">
									<?php echo $this->v['post']->getFormattedMessage(); ?>
								</div>
							</div>
							
							<?php
$outerTemplateName3ec0d4ac73bf98c5ddb84701710bbe30ffe53309 = $this->v['tpl']['template'];
$this->includeTemplate('attachmentsShow', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName3ec0d4ac73bf98c5ddb84701710bbe30ffe53309;
$this->v['tpl']['includedTemplates']['attachmentsShow'] = 1;
?>
							
							<?php if (MODULE_USER_SIGNATURE == 1 && $this->v['post']->getSignature()) { ?>
								<div class="signature">
									<?php echo $this->v['post']->getSignature(); ?>
								</div>
							<?php } ?>
							
							<?php if ($this->v['post']->editCount > 0) { ?>
								<p class="editNote smallFont light">Dieser Beitrag wurde bereits <?php echo StringUtil::formatNumeric($this->v['post']->editCount); ?> mal editiert, zuletzt von &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->editor); ?>&laquo; (<?php echo $this->pluginObjects['TemplatePluginModifierShorttime']->execute(array($this->v['post']->lastEditTime), $this); ?>)<?php if ($this->v['post']->editReason) { ?> aus folgendem Grund: <?php echo StringUtil::encodeHTML($this->v['post']->editReason); ?><?php } ?></p>
							<?php } ?>
							
							<?php if ($this->v['post']->isDeleted) { ?>
								<p class="deleteNote smallFont light">Gelöscht <?php if ($this->v['post']->userID == $this->v['post']->deletedByID) { ?>vom Autor selbst<?php } else { ?>von &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->deletedBy); ?>&laquo;<?php } ?> (<?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['post']->deleteTime), $this); ?>)<?php if ($this->v['post']->deleteReason) { ?>: <?php echo StringUtil::encodeHTML($this->v['post']->deleteReason); ?><?php } ?>
		<?php if (THREAD_EMPTY_RECYCLE_BIN_CYCLE > 0) { ?><br />Zeit bis zur endgültigen Löschung: <?php echo $this->pluginObjects['TemplatePluginModifierDatediff']->execute(array($this->v['post']->deleteTime+THREAD_EMPTY_RECYCLE_BIN_CYCLE*86400), $this); ?><?php } ?></p>
							<?php } ?>
							
							<div class="<?php echo $this->v['messageFooterClass']; ?>">
								<div class="smallButtons">
									<ul id="postButtons<?php echo $this->v['post']->postID; ?>">
										<li class="extraButton"><a href="#top" title="Zum Seitenanfang"><img src="<?php echo StyleManager::getStyle()->getIconPath('upS.png'); ?>" alt="Zum Seitenanfang" /> <span class="hidden">Zum Seitenanfang</span></a></li>
										<?php if ($this->v['thread']->canReplyThread()) { ?>
											<li><a id="postQuote<?php echo $this->v['post']->postID; ?>" href="index.php?form=PostAdd&amp;postID=<?php echo $this->v['post']->postID; ?>&amp;action=quote<?php echo SID_ARG_2ND; ?>" title="Zitieren"><img src="<?php echo StyleManager::getStyle()->getIconPath('messageQuoteS.png'); ?>" alt="" /> <span>Zitieren</span></a></li>
										<?php } ?>
										<?php if ($this->v['post']->canEditPost($this->v['board'],$this->v['thread'])) { ?>
											<li><a href="index.php?form=PostEdit&amp;postID=<?php echo $this->v['post']->postID; ?><?php echo SID_ARG_2ND; ?>" title="Bearbeiten"><img src="<?php echo StyleManager::getStyle()->getIconPath('editS.png'); ?>" alt="" /> <span>Bearbeiten</span></a></li>
										<?php } ?>
										<?php if ($this->v['this']->user->userID) { ?>
											<li><a href="index.php?form=PostReport&amp;postID=<?php echo $this->v['post']->postID; ?><?php echo SID_ARG_2ND; ?>" title="Melden"><img src="<?php echo StyleManager::getStyle()->getIconPath('postReportS.png'); ?>" alt="" /> <span>Melden</span></a></li>
										<?php } ?>
										<?php if (MODULE_USER_INFRACTION == 1 && $this->v['post']->userID && $this->v['this']->user->getPermission('admin.user.infraction.canWarnUser')) { ?>
											<li><a href="index.php?form=UserWarn&amp;userID=<?php echo $this->v['post']->userID; ?>&amp;objectType=post&amp;objectID=<?php echo $this->v['post']->postID; ?><?php echo SID_ARG_2ND; ?>" title="Verwarnen"><img src="<?php echo StyleManager::getStyle()->getIconPath('infractionWarningS.png'); ?>" alt="" /> <span>Verwarnen</span></a></li>
										<?php } ?>
										<?php if (isset($this->v['additionalSmallButtons'][$this->v['messageID']])) { ?><?php echo $this->v['additionalSmallButtons'][$this->v['messageID']]; ?><?php } ?>
									</ul>
								</div>
							</div>
							<hr />
						</div>
					</div>
					
				</div>
			</div>
		<?php } ?>
		
		<?php if ($this->v['hiddenDeletedPost'] || $this->v['hiddenIgnoredPost']) { ?>
			<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'postCycle', 'print' => false), $this); ?>
			<div class="message messageMinimized" id="hiddenPostInfo<?php echo $this->v['post']->postID; ?>">
				<div class="messageInner container-<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'postCycle'), $this); ?>">
					<a id="post<?php echo $this->v['post']->postID; ?>"></a>
					<?php if ($this->v['hiddenDeletedPost']) { ?>
						<img src="<?php echo StyleManager::getStyle()->getIconPath('postTrashM.png'); ?>" alt="" />
					<?php } else { ?>
						<img src="<?php echo StyleManager::getStyle()->getIconPath('warningM.png'); ?>" alt="" />
					<?php } ?>
					<p class="smallFont light">
						
						<?php if ( ! $this->v['hiddenDeletedPost'] || $this->v['board']->getModeratorPermission('canReadDeletedPost')) { ?>
							<a onclick="showContent('postRow<?php echo $this->v['post']->postID; ?>', 'hiddenPostInfo<?php echo $this->v['post']->postID; ?>')" title="Inhalt des Beitrags anzeigen">
						<?php } ?>
						
						<span>
							<?php if ($this->v['hiddenDeletedPost']) { ?>
								Der Beitrag<?php if ($this->v['post']->subject) { ?> &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->subject); ?>&laquo;<?php } ?> von &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->username); ?>&laquo; (<?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['post']->time), $this); ?>) wurde<?php if ($this->v['post']->deleteReason) { ?> aus folgendem Grund<?php } ?> vom <?php if ($this->v['post']->userID == $this->v['post']->deletedByID) { ?>Autor selbst<?php } else { ?>Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->deletedBy); ?>&laquo;<?php } ?> gelöscht<?php if ($this->v['post']->deleteReason) { ?>: <?php echo StringUtil::encodeHTML($this->v['post']->deleteReason); ?><?php } ?> (<?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['post']->deleteTime), $this); ?>).
							<?php } elseif ($this->v['hiddenIgnoredPost']) { ?>
								Der Beitrag<?php if ($this->v['post']->subject) { ?> &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->subject); ?>&laquo;<?php } ?> von &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->username); ?>&laquo; (<?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['post']->time), $this); ?>) wird nicht angezeigt, weil Sie den Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v['post']->username); ?>&laquo; ignorieren.
							<?php } ?>
						</span>
						
						<?php if ( ! $this->v['hiddenDeletedPost'] || $this->v['board']->getModeratorPermission('canReadDeletedPost')) { ?>
							</a>
						<?php } ?>
					</p>
				</div>
			</div>
		<?php } ?>
		
		<?php if ($this->v['sortOrder'] == 'DESC') { ?>
			<?php $this->assign("startIndex", $this->v['startIndex']-1); ?>
		<?php } else { ?>
			<?php $this->assign("startIndex", $this->v['startIndex']+1); ?>
		<?php } ?>
	<?php } } ?>
	
	<?php if (THREAD_ENABLE_QUICK_REPLY == 1 && $this->v['thread']->canReplyThread() && $this->v['this']->user->userID != 0) { ?>
		<?php
$outerTemplateName86cfebf067dd3e999921a9680375e45c46b3d5eb = $this->v['tpl']['template'];
$this->includeTemplate('threadQuickReply', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName86cfebf067dd3e999921a9680375e45c46b3d5eb;
$this->v['tpl']['includedTemplates']['threadQuickReply'] = 1;
?>
	<?php } ?>
	
	<div class="contentFooter">
		<?php echo $this->v['pagesOutput']; ?>
		
		<div id="threadEditMarked" class="optionButtons"></div>
		<div id="postEditMarked" class="optionButtons"></div>
		
		<div class="largeButtons">
			<?php if ($this->v['thread']->canReplyThread() || isset($this->v['additionalLargeButtons'])) { ?>
				<ul>
					<?php if ($this->v['thread']->canReplyThread()) { ?><li><a href="index.php?form=PostAdd&amp;threadID=<?php echo $this->v['thread']->threadID; ?><?php echo SID_ARG_2ND; ?>" id="replyButton2" title="Antworten"><img src="<?php echo StyleManager::getStyle()->getIconPath('messageAddM.png'); ?>" alt="" /> <span>Antworten</span></a></li><?php } ?>
					
					<?php if (isset($this->v['additionalLargeButtons'])) { ?><?php echo $this->v['additionalLargeButtons']; ?><?php } ?>
				</ul>
			<?php } ?>
		</div>
	</div>
	
	<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'class="container-2",class="container-1"', 'name' => 'container', 'print' => false), $this); ?>
	
	<?php if (isset($this->v['usersOnlineTotal']) || count($this->v['similarThreads']) || count($this->v['tags']) || isset($this->v['additionalBoxes'])) { ?>
		<div class="border infoBox">
			<?php if (isset($this->v['usersOnlineTotal'])) { ?>
				<div <?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'container'), $this); ?>>
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('membersM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3><?php if ($this->v['this']->user->getPermission('user.usersOnline.canView')) { ?><a href="index.php?page=UsersOnline&amp;threadID=<?php echo $this->v['thread']->threadID; ?><?php echo SID_ARG_2ND; ?>">Zurzeit <?php if ($this->v['usersOnlineTotal'] == 1) { ?>ist<?php } else { ?>sind<?php } ?> neben Ihnen <?php echo StringUtil::formatNumeric($this->v['usersOnlineTotal']); ?> Benutzer in diesem Thema unterwegs:</a><?php } else { ?>Zurzeit <?php if ($this->v['usersOnlineTotal'] == 1) { ?>ist<?php } else { ?>sind<?php } ?> neben Ihnen <?php echo StringUtil::formatNumeric($this->v['usersOnlineTotal']); ?> Benutzer in diesem Thema unterwegs:<?php } ?></h3>
						<p class="smallFont">
<?php if ($this->v['usersOnlineMembers'] > 0) { ?>
	<?php echo StringUtil::formatNumeric($this->v['usersOnlineMembers']); ?> Mitglied<?php if ($this->v['usersOnlineMembers'] != 1) { ?>er<?php } ?>
<?php } ?> 
<?php if ($this->v['usersOnlineInvisible'] > 0) { ?>
	(davon <?php echo StringUtil::formatNumeric($this->v['usersOnlineInvisible']); ?> unsichtbar)
<?php } ?>
<?php if ($this->v['usersOnlineGuests'] > 0 && $this->v['usersOnlineMembers'] > 0) { ?>und<?php } ?>
<?php if ($this->v['usersOnlineGuests'] > 0) { ?>
	<?php echo StringUtil::formatNumeric($this->v['usersOnlineGuests']); ?> Besucher
<?php } ?></p>
						<?php if (count($this->v['usersOnline'])) { ?>
							<p class="smallFont"><?php
$_length6fc681a38825553f123087bae7717c56baf21d49 = count($this->v['usersOnline']);
$_i6fc681a38825553f123087bae7717c56baf21d49 = 0;
foreach ($this->v['usersOnline'] as $this->v['userOnline']) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v['userOnline']['userID']; ?><?php echo SID_ARG_2ND; ?>"><?php echo $this->v['userOnline']['username']; ?></a><?php
if (++$_i6fc681a38825553f123087bae7717c56baf21d49 < $_length6fc681a38825553f123087bae7717c56baf21d49) { echo ', '; }
} ?></p>
							<?php if (INDEX_ENABLE_USERS_ONLINE_LEGEND && count($this->v['usersOnlineMarkings'])) { ?>
								<p class="smallFont">
								Legende: <?php
$_length2a3b0b235719b77c4a908a31c442a6935e4174fc = count($this->v['usersOnlineMarkings']);
$_i2a3b0b235719b77c4a908a31c442a6935e4174fc = 0;
foreach ($this->v['usersOnlineMarkings'] as $this->v['usersOnlineMarking']) { ?><?php echo $this->v['usersOnlineMarking']; ?><?php
if (++$_i2a3b0b235719b77c4a908a31c442a6935e4174fc < $_length2a3b0b235719b77c4a908a31c442a6935e4174fc) { echo ', '; }
} ?>
								</p>
							<?php } ?>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
			
			<?php if (count($this->v['similarThreads'])) { ?>
				<div <?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'container'), $this); ?>>
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('similarThreadsM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3>Ähnliche Themen</h3>
						<ul class="similarThreads">
							<?php
if (count($this->v['similarThreads']) > 0) {
foreach ($this->v['similarThreads'] as $this->v['similarThread']) {
?>
								<li<?php if (BOARD_THREADS_ENABLE_MESSAGE_PREVIEW) { ?> title="<?php echo StringUtil::encodeHTML($this->v['similarThread']->firstPostPreview); ?>"<?php } ?>>
									<ul class="breadCrumbs">
										<li><a href="index.php?page=Board&amp;boardID=<?php echo $this->v['similarThread']->boardID; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('boardS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['similarThread']->title); ?><?php $_langb944c8dcf701ea0942d1e452e7fe62cf8d270054 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langb944c8dcf701ea0942d1e452e7fe62cf8d270054, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
										<li>
											<a href="index.php?page=Thread&amp;threadID=<?php echo $this->v['similarThread']->threadID; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('threadS.png'); ?>" alt="" /> <?php if ($this->v['similarThread']->prefix) { ?><span class="prefix"><strong><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['similarThread']->prefix); ?><?php $_lange254ede35051c2fe1a66dd37da3ef9fd308aa9a1 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lange254ede35051c2fe1a66dd37da3ef9fd308aa9a1, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></strong></span> <?php } ?><span><?php echo StringUtil::encodeHTML($this->v['similarThread']->topic); ?></span></a>
											<span class="light">(<?php echo $this->pluginObjects['TemplatePluginModifierShorttime']->execute(array($this->v['similarThread']->time), $this); ?>)</span>
										</li>
									</ul>
								</li>
							<?php } } ?>
						</ul>
					</div>
				</div>
			<?php } ?>
			
			<?php if (count($this->v['tags'])) { ?>
				<div <?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'container'), $this); ?>>
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('tagM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3>Verwendete Tags</h3>
						<p class="smallFont"><?php
$_length81ab118a3bf35dd343bf17aef99974d2e09c5076 = count($this->v['tags']);
$_i81ab118a3bf35dd343bf17aef99974d2e09c5076 = 0;
foreach ($this->v['tags'] as $this->v['tag']) { ?><a href="index.php?page=TaggedObjects&amp;tagID=<?php echo $this->v['tag']->getID(); ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['tag']->getName()); ?></a><?php
if (++$_i81ab118a3bf35dd343bf17aef99974d2e09c5076 < $_length81ab118a3bf35dd343bf17aef99974d2e09c5076) { echo ', '; }
} ?></p>
					</div>
				</div>
			<?php } ?>

			<?php if (isset($this->v['additionalBoxes'])) { ?><?php echo $this->v['additionalBoxes']; ?><?php } ?>
		</div>
	<?php } ?>
	
	<div class="pageOptions">
		<?php if (isset($this->v['additionalPageOptions'])) { ?><?php echo $this->v['additionalPageOptions']; ?><?php } ?>

		<?php if (MODULE_THREAD_MARKING_AS_DONE && $this->v['board']->enableMarkingAsDone && $this->v['this']->user->userID && $this->v['this']->user->userID == $this->v['thread']->userID && $this->v['board']->getPermission('canMarkAsDoneOwnThread') &&  ! $this->v['thread']->isDone) { ?>
			<a href="index.php?action=ThreadMarkAsDone&amp;threadID=<?php echo $this->v['thread']->threadID; ?>&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('doneS.png'); ?>" alt="" /> <span>Als erledigt markieren</span></a>
		<?php } ?>

		<?php if ($this->v['this']->user->userID) { ?>
			<?php if ( ! $this->v['thread']->subscribed) { ?>
				<a href="index.php?action=ThreadSubscribe&amp;threadID=<?php echo $this->v['thread']->threadID; ?>&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('subscribeS.png'); ?>" alt="" /> <span>Thema abonnieren</span></a>
			<?php } else { ?>
				<a href="index.php?action=ThreadUnsubscribe&amp;threadID=<?php echo $this->v['thread']->threadID; ?>&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('unsubscribeS.png'); ?>" alt="" /> <span>Thema abbestellen</span></a>
			<?php } ?>
		<?php } ?>
		
		<?php if ($this->v['enableRating'] && $this->v['board']->getPermission('canRateThread')) { ?>
			<?php if ($this->v['thread']->userRating === null || $this->v['thread']->userRating > 0) { ?>
				<script type="text/javascript" src="<?php echo RELATIVE_WBB_DIR; ?>js/Rating.class.js"></script>
				<form method="post" action="index.php?page=Thread">
					<div>
						<input type="hidden" name="threadID" value="<?php echo $this->v['thread']->threadID; ?>" />
						<?php echo SID_INPUT_TAG; ?>
						<input type="hidden" name="pageNo" value="<?php echo $this->v['pageNo']; ?>" />
						<input type="hidden" id="threadRating" name="rating" value="0" />

						<span class="hidden" id="threadRatingSpan"></span>

						<span>Thema bewerten</span>

						<noscript>
							<div>
								<select id="threadRatingSelect" name="rating">
									<option value="1"<?php if ($this->v['thread']->userRating == 1) { ?> selected="selected"<?php } ?>>1</option>
									<option value="2"<?php if ($this->v['thread']->userRating == 2) { ?> selected="selected"<?php } ?>>2</option>
									<option value="3"<?php if ($this->v['thread']->userRating == 3) { ?> selected="selected"<?php } ?>>3</option>
									<option value="4"<?php if ($this->v['thread']->userRating == 4) { ?> selected="selected"<?php } ?>>4</option>
									<option value="5"<?php if ($this->v['thread']->userRating == 5) { ?> selected="selected"<?php } ?>>5</option>
								</select>
								<input type="image" class="inputImage" src="<?php echo StyleManager::getStyle()->getIconPath('submitS.png'); ?>" alt="Absenden" />
							</div>
						</noscript>
					</div>
				</form>
				
				<script type="text/javascript">
					//<![CDATA[
					new Rating('threadRating', <?php echo intval($this->v['thread']->userRating); ?>);
					//]]>
				</script>
			<?php } ?>
		<?php } ?>
	</div>
	<?php
$outerTemplateName6a1d3d8d8f4281dab1192c9f04966bffb8b2415e = $this->v['tpl']['template'];
$this->includeTemplate('boardQuickJump', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName6a1d3d8d8f4281dab1192c9f04966bffb8b2415e;
$this->v['tpl']['includedTemplates']['boardQuickJump'] = 1;
?>
</div>

<?php
$outerTemplateName8de179f534893719cb9f597ef865ab4a5dec7a01 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName8de179f534893719cb9f597ef865ab4a5dec7a01;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>