<?php
/**
* WoltLab Community Framework
* Template: threadAdd
* Compiled at: Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'threadAdd';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCounter'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCounter.class.php');
$this->pluginObjects['TemplatePluginFunctionCounter'] = new TemplatePluginFunctionCounter;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
?><?php
$outerTemplateName7265e829edc940d478990b3f9da8341dd070e64d = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7265e829edc940d478990b3f9da8341dd070e64d;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Neues Thema erstellen - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['board']->title); ?><?php $_langd35f3bb1c912d3d5d67e354ad158c11a2bbf6b9c = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langd35f3bb1c912d3d5d67e354ad158c11a2bbf6b9c, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang6466a78c7aca9f0ace8144bc1b8a0ddd781e4f54 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang6466a78c7aca9f0ace8144bc1b8a0ddd781e4f54, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>

	<?php
$outerTemplateName1f8407bff6b40d3aa33baa7fb75e7ac5642a9201 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName1f8407bff6b40d3aa33baa7fb75e7ac5642a9201;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	
	<?php
$outerTemplateName7e8a1a4612e995d2da4a2098c45bbadfbb8caa64 = $this->v['tpl']['template'];
$this->includeTemplate('imageViewer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7e8a1a4612e995d2da4a2098c45bbadfbb8caa64;
$this->v['tpl']['includedTemplates']['imageViewer'] = 1;
?>
	
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/TabbedPane.class.js"></script>
	<script type="text/javascript">
		//<![CDATA[
		var INLINE_IMAGE_MAX_WIDTH = <?php echo INLINE_IMAGE_MAX_WIDTH; ?>; 
		//]]>
	</script>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/ImageResizer.class.js"></script>
	<?php if ($this->v['canUseBBCodes']) { ?><?php
$outerTemplateNamebd59f90079af95f17431eb7df45aaec237d91b55 = $this->v['tpl']['template'];
$this->includeTemplate("wysiwyg", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamebd59f90079af95f17431eb7df45aaec237d91b55;
$this->v['tpl']['includedTemplates']["wysiwyg"] = 1;
?><?php } ?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateName090202c7d0a45446b8e6dc10b40f9706cc3a7c41 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName090202c7d0a45446b8e6dc10b40f9706cc3a7c41;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<?php
$outerTemplateName35be59ea5f64d60342345f2376cdbee7d72d73c5 = $this->v['tpl']['template'];
$this->includeTemplate("navigation", array('showBoard' => true), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName35be59ea5f64d60342345f2376cdbee7d72d73c5;
$this->v['tpl']['includedTemplates']["navigation"] = 1;
?>
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('threadNewL.png'); ?>" alt="" />
		<div class="headlineContainer">
			<h2>Neues Thema erstellen</h2>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php if ($this->v['errorField']) { ?>
		<p class="error">Ihre Angaben sind ungültig. Bitte überprüfen Sie die markierten Eingabefelder.</p>
	<?php } ?>
	
	<?php if (isset($this->v['preview'])) { ?>
		<div class="border messagePreview">
			<div class="containerHead">
				<h3>Vorschau der neuen Nachricht</h3>
			</div>
			<div class="message content">
				<div class="messageInner container-1">
					<?php if ($this->v['subject']) { ?>
						<h4><?php echo StringUtil::encodeHTML($this->v['subject']); ?></h4>
					<?php } ?>
					<div class="messageBody">
						<div><?php echo $this->v['preview']; ?></div>
					</div>
				</div>
			</div>
		</div>
	<?php } ?>
	
	<form enctype="multipart/form-data" method="post" action="index.php?form=ThreadAdd&amp;boardID=<?php echo $this->v['board']->boardID; ?>">
		<div class="border content">
			<div class="container-1">
	
				<?php if ($this->v['board']->getModeratorPermission('canPinThread') || $this->v['board']->getModeratorPermission('canStartAnnouncement')) { ?>
					<fieldset>
						<legend>Themenstatus</legend>
						
						<div class="formGroup">
							<div class="formGroupLabel">
								Status
							</div>
							<div class="formGroupField">
								<fieldset>
									<legend>Status</legend>
									<div class="formField">
										<ul class="formOptions">
											<li><label><input onclick="openList('boards', { setVisible: false })" type="radio" name="isImportant" value="0" <?php if ($this->v['isImportant'] == 0) { ?>checked="checked" <?php } ?>tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" /> <img src="<?php echo StyleManager::getStyle()->getIconPath('threadM.png'); ?>" alt="" /> Normal</label></li>
											<?php if ($this->v['board']->getModeratorPermission('canPinThread')) { ?><li><label><input onclick="openList('boards', { setVisible: false })" type="radio" name="isImportant" value="1" <?php if ($this->v['isImportant'] == 1) { ?>checked="checked" <?php } ?>tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" /> <img src="<?php echo StyleManager::getStyle()->getIconPath('threadImportantM.png'); ?>" alt="" /> wichtig</label></li><?php } ?>
											<?php if ($this->v['board']->getModeratorPermission('canStartAnnouncement')) { ?><li><label><input onclick="openList('boards', { setVisible: true })" type="radio" name="isImportant" value="2" <?php if ($this->v['isImportant'] == 2) { ?>checked="checked" <?php } ?>tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" /> <img src="<?php echo StyleManager::getStyle()->getIconPath('threadAnnouncementM.png'); ?>" alt="" /> Ankündigung</label></li><?php } ?>
										</ul>
									</div>
								</fieldset>
							</div>
						</div>
						
						<?php if ($this->v['board']->getModeratorPermission('canStartAnnouncement')) { ?>
							<?php if ($this->v['isImportant'] != 2) { ?>
								<script type="text/javascript">
									//<![CDATA[
									onloadEvents.push(function() { document.getElementById('boards').style.display = 'none'; });
									//]]>
								</script>
							<?php } ?>
							<div id="boards" class="formElement">
								<div class="formFieldLabel">
									<label>Foren für diese Ankündigung</label>
								</div>
								<div class="formField longSelect">
									<select name="boardIDs[]" id="boardIDs" multiple="multiple" size="10" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>">
										<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['boardOptions'], 'selected' => $this->v['boardIDs'], 'disableEncoding' => true), $this); ?>
									</select>
								</div>
								<div class="formFieldDesc">
									<p>Geben Sie an, in welchen Foren die Ankündigung angezeigt werden soll. Die Ankündigung wird automatisch mit dem Forum verknüpft, in dem sie erstellt wurde.</p>
									<p>Mehrfache Markierungen sind durch zusätzliches Drücken der Taste &raquo;Strg/Ctrl&laquo; (Windows) oder &raquo;Befehl/Command&laquo; (Mac OS) möglich.</p>
								</div>
							</div>
						<?php } ?>
					</fieldset>
				<?php } ?>
					
				<fieldset>
					<legend>Beitragsinformationen</legend>
					
					<?php if (count($this->v['availableLanguages']) > 1) { ?>
						<div class="formElement">
							<div class="formFieldLabel">
								<label for="languageID">Sprache</label>
							</div>
							<div class="formField">
								<select name="languageID" id="languageID" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>">
									<?php
if (count($this->v['availableLanguages']) > 0) {
foreach ($this->v['availableLanguages'] as $this->v['availableLanguage']) {
?>
									<option value="<?php echo $this->v['availableLanguage']['languageID']; ?>"
										<?php if ($this->v['availableLanguage']['languageID'] == $this->v['languageID']) { ?> selected="selected"<?php } ?>><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.global.language.<?php echo $this->v['availableLanguage']['languageCode']; ?><?php $_langca79c4ec0da8dc529047ab6ab8afccbb3e5406e5 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langca79c4ec0da8dc529047ab6ab8afccbb3e5406e5, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></option>
									<?php } } ?>
								</select>
							</div>
						</div>
					<?php } ?>
					
					<?php if ($this->v['board']->hasPrefixes() && $this->v['board']->getPermission('canUsePrefix')) { ?>
						<div class="formElement<?php if ($this->v['errorField'] == 'prefix') { ?> formError<?php } ?>">
							<div class="formFieldLabel">
								<label for="prefix">Präfix</label>
							</div>
							<div class="formField">
								<select name="prefix" id="prefix" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>">
									<option value=""></option>
									<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['board']->getPrefixOptions(), 'selected' => $this->v['prefix']), $this); ?>
								</select>
								<?php if ($this->v['errorField'] == 'prefix') { ?>
									<p class="innerError">
										<?php if ($this->v['errorType'] == 'empty') { ?>Bitte wählen Sie einen Präfix aus!<?php } ?>
										<?php if ($this->v['errorType'] == 'invalid') { ?>Sie haben einen ungültigen Präfix ausgewählt.<?php } ?>
									</p>
								<?php } ?>
							</div>
						</div>
					<?php } ?>
					
					<?php if ( ! $this->v['this']->user->userID) { ?>
						<div class="formElement<?php if ($this->v['errorField'] == 'username') { ?> formError<?php } ?>">
							<div class="formFieldLabel">
								<label for="username">Benutzername</label>
							</div>
							<div class="formField">
								<input type="text" class="inputText" name="username" id="username" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
								<?php if ($this->v['errorField'] == 'username') { ?>
									<p class="innerError">
										<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
										<?php if ($this->v['errorType'] == 'notValid') { ?>Sie haben einen ungültigen Benutzernamen eingegeben.<?php } ?>
										<?php if ($this->v['errorType'] == 'notAvailable') { ?>Dieser Benutzername ist bereits vergeben.<?php } ?>
									</p>
								<?php } ?>
							</div>
						</div>
					<?php } ?>
					
					<div class="formElement<?php if ($this->v['errorField'] == 'subject') { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="subject">Überschrift</label>
						</div>
						<div class="formField">
							<input type="text" class="inputText" name="subject" id="subject" value="<?php echo StringUtil::encodeHTML($this->v['subject']); ?>" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
							<?php if ($this->v['errorField'] == 'subject') { ?>
								<p class="innerError">
									<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
					
					<?php if (MODULE_TAGGING && THREAD_ENABLE_TAGS && $this->v['board']->getPermission('canSetTags')) { ?><?php
$outerTemplateNamef6ff7fb9682fb75944cfa0dead9f2fddb770e807 = $this->v['tpl']['template'];
$this->includeTemplate('tagAddBit', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamef6ff7fb9682fb75944cfa0dead9f2fddb770e807;
$this->v['tpl']['includedTemplates']['tagAddBit'] = 1;
?><?php } ?>
					
					<?php if (isset($this->v['additionalInformationFields'])) { ?><?php echo $this->v['additionalInformationFields']; ?><?php } ?>
				</fieldset>
				
				<fieldset>
					<legend>Beitrag</legend>
					
					<div class="editorFrame formElement<?php if ($this->v['errorField'] == 'text') { ?> formError<?php } ?>" id="textDiv">
	
						<div class="formFieldLabel">
							<label for="text">Beitrag</label>
						</div>
						
						<div class="formField">				
							<textarea name="text" id="text" rows="15" cols="40" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>"><?php echo StringUtil::encodeHTML($this->v['text']); ?></textarea>
							<?php if ($this->v['errorField'] == 'text') { ?>
								<p class="innerError">
									<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
									<?php if ($this->v['errorType'] == 'tooLong') { ?>Ihre Nachricht ist zu lang. Es stehen maximal <?php echo StringUtil::formatNumeric($this->v['maxTextLength']); ?> Zeichen zur Verfügung.<?php } ?>
									<?php if ($this->v['errorType'] == 'censoredWordsFound') { ?>Ihre Nachricht enthält folgende zensierte Wörter: <?php
$_length3359fb983e757e5956990f62ca104f22935aefce = count($this->v['censoredWords']);
$_i3359fb983e757e5956990f62ca104f22935aefce = 0;
foreach ($this->v['censoredWords'] as $this->v['censoredWord'] => $this->v['number']) { ?><?php echo StringUtil::encodeHTML($this->v['censoredWord']); ?><?php if ($this->v['number'] > 1) { ?> (<?php echo StringUtil::formatNumeric($this->v['number']); ?>x)<?php } ?><?php
if (++$_i3359fb983e757e5956990f62ca104f22935aefce < $_length3359fb983e757e5956990f62ca104f22935aefce) { echo ', '; }
} ?><?php } ?>
									<?php if ($this->v['errorType'] == 'tooShort') { ?>Der Beitrag ist zu kurz. Der Beitrag muss mindestens <?php echo StringUtil::formatNumeric($this->v['minCharLength']); ?> Zeichen lang sein und <?php echo StringUtil::formatNumeric($this->v['minWordCount']); ?> <?php if ($this->v['minWordCount'] == 1) { ?>Wort<?php } else { ?>Wörter<?php } ?> enthalten.<?php } ?>
								</p>
							<?php } ?>
						</div>
						
					</div>
					
					<?php
$outerTemplateName08e1aee3cf801b8a811b781ffe0aa60d45a8d81e = $this->v['tpl']['template'];
ob_start();
$this->includeTemplate('postFormSettings', array(), (1 ? 1 : 0));
$this->append('additionalSettings', ob_get_contents()); ob_end_clean();
$this->v['tpl']['template'] = $outerTemplateName08e1aee3cf801b8a811b781ffe0aa60d45a8d81e;
$this->v['tpl']['includedTemplates']['postFormSettings'] = 1;
?>
					<?php
$outerTemplateName570fc872c74878fb30649224d285272eddc98229 = $this->v['tpl']['template'];
$this->includeTemplate('messageFormTabs', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName570fc872c74878fb30649224d285272eddc98229;
$this->v['tpl']['includedTemplates']['messageFormTabs'] = 1;
?>
					
				</fieldset>
				
				<?php
$outerTemplateName843c20560829aae5beec45098fd612f6cf15c07b = $this->v['tpl']['template'];
$this->includeTemplate('captcha', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName843c20560829aae5beec45098fd612f6cf15c07b;
$this->v['tpl']['includedTemplates']['captcha'] = 1;
?>
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
			</div>
		</div>
		
		<div class="formSubmit">
			<input type="submit" name="send" accesskey="s" value="Absenden" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
			<input type="submit" name="preview" accesskey="p" value="Vorschau" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
			<input type="reset" name="reset" accesskey="r" value="Zurücksetzen" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
			<?php echo SID_INPUT_TAG; ?>
			<input type="hidden" name="idHash" value="<?php echo StringUtil::encodeHTML($this->v['idHash']); ?>" />
		</div>
	</form>

</div>

<?php
$outerTemplateNamea252993cfb9dbf3822a9e6243a60c22eac49f1e7 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamea252993cfb9dbf3822a9e6243a60c22eac49f1e7;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>