<?php
/**
* WoltLab Community Framework
* Template: navigation
* Compiled at: Wed, 28 May 2014 19:46:43 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'navigation';
?>
<ul class="breadCrumbs">
	<?php if ( ! isset($this->v['hideRoot'])) { ?>
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang91731e9718c858d83140b4801ae6560384c99d91 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang91731e9718c858d83140b4801ae6560384c99d91, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	<?php } ?>
	
	<?php
if (count($this->v['board']->getParentBoards()) > 0) {
foreach ($this->v['board']->getParentBoards() as $this->v['parentBoard']) {
?>
		<li><a href="index.php?page=Board&amp;boardID=<?php echo $this->v['parentBoard']->boardID; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php ob_start(); ?><?php echo $this->v['parentBoard']->getIconName(); ?>S.png<?php $_icon34ffaf15fa044b6433a90cefc0a0441a2cee8f77 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon34ffaf15fa044b6433a90cefc0a0441a2cee8f77); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['parentBoard']->title); ?><?php $_lang8d4b36d88b611e398faaf49c5b90074f6758452d = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang8d4b36d88b611e398faaf49c5b90074f6758452d, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	<?php } } ?>
	
	<?php if (isset($this->v['showBoard']) || isset($this->v['showThread'])) { ?>
		<li><a href="index.php?page=Board&amp;boardID=<?php echo $this->v['board']->boardID; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php ob_start(); ?><?php echo $this->v['board']->getIconName(); ?>S.png<?php $_icone6559efd8bca639a31fc164035c87209d8414c38 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icone6559efd8bca639a31fc164035c87209d8414c38); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['board']->title); ?><?php $_lang1964f7a3e2388667494f9fd3aae7ea522df6d554 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang1964f7a3e2388667494f9fd3aae7ea522df6d554, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	<?php } ?>
	
	<?php if (isset($this->v['showThread'])) { ?>
		<li><a href="index.php?page=Thread&amp;threadID=<?php echo $this->v['thread']->threadID; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('threadS.png'); ?>" alt="" /> <?php if ($this->v['thread']->prefix) { ?><span class="prefix"><strong><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['thread']->prefix); ?><?php $_lange2e5205a95a70c21d1337c950710495bfc1e1a5c = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lange2e5205a95a70c21d1337c950710495bfc1e1a5c, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></strong></span> <?php } ?><span><?php echo StringUtil::encodeHTML($this->v['thread']->topic); ?></span></a> &raquo;</li>
	<?php } ?>
</ul>