<?php
/**
* WoltLab Community Framework
* Template: postAdd
* Compiled at: Sun, 08 Jun 2014 22:15:40 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'postAdd';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCounter'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCounter.class.php');
$this->pluginObjects['TemplatePluginFunctionCounter'] = new TemplatePluginFunctionCounter;
}
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginModifierTime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierTime.class.php');
$this->pluginObjects['TemplatePluginModifierTime'] = new TemplatePluginModifierTime;
}
?><?php
$outerTemplateName2479de0ad146336766eb3dfdee1a5db57b3b2429 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName2479de0ad146336766eb3dfdee1a5db57b3b2429;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Neue Antwort erstellen - <?php if ($this->v['thread']->prefix) { ?><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['thread']->prefix); ?><?php $_lang8fe60a92a43f69eff22333bd31299b5e21e6b3cc = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang8fe60a92a43f69eff22333bd31299b5e21e6b3cc, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> <?php } ?><?php echo StringUtil::encodeHTML($this->v['thread']->topic); ?> - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['board']->title); ?><?php $_langf83a597cb1ca5500dfa1d3cd9a2d51d4307d1373 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langf83a597cb1ca5500dfa1d3cd9a2d51d4307d1373, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langa2c1cc8317f144d7c4f0dc2fd1230745a8ca8c58 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langa2c1cc8317f144d7c4f0dc2fd1230745a8ca8c58, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	
	<?php
$outerTemplateNamec93e43fa7bd7f28f2b8c674fece5c1de86e86931 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamec93e43fa7bd7f28f2b8c674fece5c1de86e86931;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	
	<?php
$outerTemplateName7443b45f3e0e5206dc820169dfc68bd96c7506f7 = $this->v['tpl']['template'];
$this->includeTemplate('imageViewer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7443b45f3e0e5206dc820169dfc68bd96c7506f7;
$this->v['tpl']['includedTemplates']['imageViewer'] = 1;
?>
	
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/TabbedPane.class.js"></script>
	<script type="text/javascript">
		//<![CDATA[
		var INLINE_IMAGE_MAX_WIDTH = <?php echo INLINE_IMAGE_MAX_WIDTH; ?>; 
		//]]>
	</script>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/ImageResizer.class.js"></script>
	<?php
$outerTemplateName1081b526ec0d9726c55391360dd3c9a7e4745b14 = $this->v['tpl']['template'];
$this->includeTemplate('multiQuote', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName1081b526ec0d9726c55391360dd3c9a7e4745b14;
$this->v['tpl']['includedTemplates']['multiQuote'] = 1;
?>
	<?php if ($this->v['canUseBBCodes']) { ?><?php
$outerTemplateName4df0320492378aeba486bd15ec4e054b97fd00e5 = $this->v['tpl']['template'];
$this->includeTemplate("wysiwyg", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName4df0320492378aeba486bd15ec4e054b97fd00e5;
$this->v['tpl']['includedTemplates']["wysiwyg"] = 1;
?><?php } ?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>

<?php
$outerTemplateNamedbfa459982bc5b31734b024746ffff98b59d1dd6 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamedbfa459982bc5b31734b024746ffff98b59d1dd6;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<?php
$outerTemplateNamec79066fe093053aa1ae6eab87ab8d01250941e21 = $this->v['tpl']['template'];
$this->includeTemplate("navigation", array('showThread' => true), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamec79066fe093053aa1ae6eab87ab8d01250941e21;
$this->v['tpl']['includedTemplates']["navigation"] = 1;
?>
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('messageAddL.png'); ?>" alt="" />
		<div class="headlineContainer">
			<h2>Neue Antwort erstellen</h2>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php if ($this->v['errorField']) { ?>
		<p class="error">Ihre Angaben sind ungültig. Bitte überprüfen Sie die markierten Eingabefelder.</p>
	<?php } ?>
	
	<?php if ($this->v['oldThreadWarning']) { ?>
		<p class="warning">Achtung! Die letzte Antwort auf dieses Thema liegt mehr als <?php echo StringUtil::formatNumeric($this->v['oldThreadWarning']); ?> Tage 
	zurück. Das Thema ist womöglich bereits veraltet. Bitte erstellen Sie ggf. ein <a href="index.php?form=ThreadAdd&amp;boardID=<?php echo $this->v['boardID']; ?><?php echo SID_ARG_2ND; ?>">neues Thema</a>.</p>
	<?php } ?>

	<?php if (MODULE_THREAD_MARKING_AS_DONE == 1 && $this->v['board']->enableMarkingAsDone == 1 && $this->v['thread']->isDone == 1) { ?>
		<p class="warning">Achtung! Dieses Thema wurde als erledigt markiert. Bitte erstellen Sie ggf. ein <a href="index.php?form=ThreadAdd&amp;boardID=<?php echo $this->v['boardID']; ?><?php echo SID_ARG_2ND; ?>">neues Thema</a>.</p>
	<?php } ?>
	
	<?php if (isset($this->v['preview'])) { ?>
		<div class="border messagePreview">
			<div class="containerHead">
				<h3>Vorschau der neuen Nachricht</h3>
			</div>
			
			<div class="message content">
				<div class="messageInner container-1">
					<?php if ($this->v['subject']) { ?>
						<h4><?php echo StringUtil::encodeHTML($this->v['subject']); ?></h4>
					<?php } ?>
					<div class="messageBody">
						<div><?php echo $this->v['preview']; ?></div>
					</div>
				</div>
			</div>
		</div>
	<?php } ?>
	
	<form enctype="multipart/form-data" method="post" action="index.php?form=PostAdd&amp;threadID=<?php echo $this->v['thread']->threadID; ?>">
		<div class="border content">
			<div class="container-1">
			
				<fieldset>
					<legend>Beitragsinformationen</legend>
					
					<?php if ($this->v['this']->user->userID == 0) { ?>
						<div class="formElement<?php if ($this->v['errorField'] == 'username') { ?> formError<?php } ?>">
							<div class="formFieldLabel">
								<label for="username">Benutzername</label>
							</div>
							<div class="formField">
								<input type="text" class="inputText" name="username" id="username" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
								<?php if ($this->v['errorField'] == 'username') { ?>
									<p class="innerError">
										<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
										<?php if ($this->v['errorType'] == 'notValid') { ?>Sie haben einen ungültigen Benutzernamen eingegeben.<?php } ?>
										<?php if ($this->v['errorType'] == 'notAvailable') { ?>Dieser Benutzername ist bereits vergeben.<?php } ?>
									</p>
								<?php } ?>
							</div>
						</div>
					<?php } ?>
					
					<div class="formElement<?php if ($this->v['errorField'] == 'subject') { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="subject">Überschrift</label>
						</div>
						<div class="formField">
							<input type="text" class="inputText" id="subject" name="subject" value="<?php echo StringUtil::encodeHTML($this->v['subject']); ?>" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
							<?php if ($this->v['errorField'] == 'subject') { ?>
								<p class="innerError">
									<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
				
					<?php if (isset($this->v['additionalInformationFields'])) { ?><?php echo $this->v['additionalInformationFields']; ?><?php } ?>
				</fieldset>
			
				<fieldset>
					<legend>Beitrag</legend>
				
					<div class="editorFrame formElement<?php if ($this->v['errorField'] == 'text') { ?> formError<?php } ?>" id="textDiv">
						<div class="formFieldLabel">
							<label for="text">Beitrag</label>
						</div>
						<div class="formField">
							<textarea name="text" id="text" rows="15" cols="40" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>"><?php echo StringUtil::encodeHTML($this->v['text']); ?></textarea>
							<?php if ($this->v['errorField'] == 'text') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
								<?php if ($this->v['errorType'] == 'tooLong') { ?>Ihre Nachricht ist zu lang. Es stehen maximal <?php echo StringUtil::formatNumeric($this->v['maxTextLength']); ?> Zeichen zur Verfügung.<?php } ?>
								<?php if ($this->v['errorType'] == 'censoredWordsFound') { ?>Ihre Nachricht enthält folgende zensierte Wörter: <?php
$_lengthc476c918feff9f3063724c5200cdc250cb18a009 = count($this->v['censoredWords']);
$_ic476c918feff9f3063724c5200cdc250cb18a009 = 0;
foreach ($this->v['censoredWords'] as $this->v['censoredWord'] => $this->v['number']) { ?><?php echo StringUtil::encodeHTML($this->v['censoredWord']); ?><?php if ($this->v['number'] > 1) { ?> (<?php echo StringUtil::formatNumeric($this->v['number']); ?>x)<?php } ?><?php
if (++$_ic476c918feff9f3063724c5200cdc250cb18a009 < $_lengthc476c918feff9f3063724c5200cdc250cb18a009) { echo ', '; }
} ?><?php } ?>
								<?php if ($this->v['errorType'] == 'tooShort') { ?>Der Beitrag ist zu kurz. Der Beitrag muss mindestens <?php echo StringUtil::formatNumeric($this->v['minCharLength']); ?> Zeichen lang sein und <?php echo StringUtil::formatNumeric($this->v['minWordCount']); ?> <?php if ($this->v['minWordCount'] == 1) { ?>Wort<?php } else { ?>Wörter<?php } ?> enthalten.<?php } ?>
							</p>
							<?php } ?>
						</div>
					</div>
			
					<?php
$outerTemplateName86eb773be6a857cc775cca3b4ff1f69b110bc872 = $this->v['tpl']['template'];
ob_start();
$this->includeTemplate('postFormSettings', array(), (1 ? 1 : 0));
$this->append('additionalSettings', ob_get_contents()); ob_end_clean();
$this->v['tpl']['template'] = $outerTemplateName86eb773be6a857cc775cca3b4ff1f69b110bc872;
$this->v['tpl']['includedTemplates']['postFormSettings'] = 1;
?>
					<?php
$outerTemplateName6c29c99e68280265b4a3858ac929b76ca1863353 = $this->v['tpl']['template'];
$this->includeTemplate('messageFormTabs', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName6c29c99e68280265b4a3858ac929b76ca1863353;
$this->v['tpl']['includedTemplates']['messageFormTabs'] = 1;
?>
						
				</fieldset>
				
				<?php
$outerTemplateName8e41e4553bb08ed612c1510e1bfee9d287ae9ed3 = $this->v['tpl']['template'];
$this->includeTemplate('captcha', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName8e41e4553bb08ed612c1510e1bfee9d287ae9ed3;
$this->v['tpl']['includedTemplates']['captcha'] = 1;
?>
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
			</div>
		</div>
		
		<div class="formSubmit">
			<input type="submit" name="send" accesskey="s" value="Absenden" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
			<input type="submit" name="preview" accesskey="p" value="Vorschau" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
			<input type="reset" name="reset" accesskey="r" value="Zurücksetzen" tabindex="<?php echo $this->pluginObjects['TemplatePluginFunctionCounter']->execute(array('name' => 'tabindex'), $this); ?>" />
			<input type="hidden" name="postID" value="<?php echo $this->v['postID']; ?>" />
			<?php echo SID_INPUT_TAG; ?>
			<input type="hidden" name="idHash" value="<?php echo StringUtil::encodeHTML($this->v['idHash']); ?>" />
		</div>
	</form>
	
	<h2><?php if (count($this->v['posts']) == 1) { ?>Der erste Beitrag<?php } else { ?>Die letzten <?php echo StringUtil::formatNumeric(count($this->v['posts'])); ?> Beiträge<?php } ?></h2>
	
	<?php $this->assign('startIndex', $this->v['items']); ?>
	<?php
if (count($this->v['posts']) > 0) {
foreach ($this->v['posts'] as $this->v['post']) {
?>
		<?php $this->assign("author", $this->v['post']->getUser()); ?>
		<?php $this->assign("messageID", $this->v['post']->postID); ?>
		
		<script type="text/javascript">
			//<![CDATA[
			quoteData.set('post-<?php echo $this->v['post']->postID; ?>', {
				objectID: <?php echo $this->v['post']->postID; ?>,
				objectType: 'post',
				quotes: <?php echo $this->v['post']->isQuoted(); ?>,
				author: '<?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['post']->username), $this)); ?>',
				url: 'index.php?page=Thread&postID=<?php echo $this->v['post']->postID; ?>#post<?php echo $this->v['post']->postID; ?>'
			});
			//]]>
		</script>
		
		<div class="message content">
			<div class="messageInner container-<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => '1,2'), $this); ?>">
				<div class="messageHeader">
					<p class="messageCount">
						<a href="index.php?page=Thread&amp;postID=<?php echo $this->v['post']->postID; ?>#post<?php echo $this->v['post']->postID; ?>" title="Permalink zum <?php echo StringUtil::formatNumeric($this->v['startIndex']); ?>. Beitrag" class="messageNumber"><?php echo StringUtil::formatNumeric($this->v['startIndex']); ?></a>
					</p>
					
					<div class="containerIcon">
						<?php if ($this->v['author']->getAvatar()) { ?>
							<?php $this->assign('x', $this->v['author']->getAvatar()->setMaxSize(24,24)); ?>
							<?php if ($this->v['author']->userID) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v['author']->userID; ?><?php echo SID_ARG_2ND; ?>" title="<?php $this->tagStack[] = array('lang', array('username' => StringUtil::encodeHTML($this->v['author']->username))); ob_start(); ?>wcf.user.viewProfile<?php $_lang03b1b828d8e55e99d60a8d12c27f24fe4ce823c3 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang03b1b828d8e55e99d60a8d12c27f24fe4ce823c3, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>"><?php } ?><?php echo $this->v['author']->getAvatar(); ?><?php if ($this->v['author']->userID) { ?></a><?php } ?>
						<?php } else { ?>
							<?php if ($this->v['author']->userID) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v['author']->userID; ?><?php echo SID_ARG_2ND; ?>" title="<?php $this->tagStack[] = array('lang', array('username' => StringUtil::encodeHTML($this->v['author']->username))); ob_start(); ?>wcf.user.viewProfile<?php $_lang241fa3204dd0dafefe40e02ab68f47e59cceace3 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang241fa3204dd0dafefe40e02ab68f47e59cceace3, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>"><?php } ?><img src="<?php echo RELATIVE_WCF_DIR; ?>images/avatars/avatar-default.png" alt="" style="width: 24px; height: 24px" /><?php if ($this->v['author']->userID) { ?></a><?php } ?>
						<?php } ?>
					</div>
					<div class="containerContent">
						<p class="light smallFont"><?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['post']->time), $this); ?></p>
						<p class="light smallFont">Von <?php if ($this->v['author']->userID) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v['author']->userID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['post']->username); ?></a><?php } else { ?><?php echo StringUtil::encodeHTML($this->v['post']->username); ?><?php } ?></p>
					</div>
				</div>
				<?php if ($this->v['post']->subject) { ?>
					<h3><?php echo StringUtil::encodeHTML($this->v['post']->subject); ?></h3>
				<?php } ?>
				<div class="messageBody">
					<div id="postText<?php echo $this->v['post']->postID; ?>">
						<?php echo $this->v['post']->getFormattedMessage(); ?>
					</div>
				</div>
				<?php
$outerTemplateName81d7c7feb3e0c1bd07f9bd825a04e73480f4521a = $this->v['tpl']['template'];
$this->includeTemplate('attachmentsShow', array('attachments' => $this->v['postAttachments']), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName81d7c7feb3e0c1bd07f9bd825a04e73480f4521a;
$this->v['tpl']['includedTemplates']['attachmentsShow'] = 1;
?>
				<div class="messageFooter">
					<div class="smallButtons">
						<ul id="postButtons<?php echo $this->v['post']->postID; ?>">
							<li class="extraButton"><a href="#top" title="Zum Seitenanfang"><img src="<?php echo StyleManager::getStyle()->getIconPath('upS.png'); ?>" alt="" title="Zum Seitenanfang" /> <span class="hidden">Zum Seitenanfang</span></a></li>
						</ul>
					</div>
				</div>
				<hr />
			</div>
		</div>
		<?php $this->assign('startIndex', $this->v['startIndex']-1); ?>
	<?php } } ?>

	<?php if ($this->v['insertQuotes'] == 1) { ?>
		<script type="text/javascript">
			//<![CDATA[
			document.observe("dom:loaded", function() {
				window.setTimeout(function() {
					multiQuoteManagerObj.insertParentQuotes('post', <?php echo $this->v['thread']->threadID; ?>);
				}, 500);
			});
			//]]>
		</script>
	<?php } ?>
</div>

<?php
$outerTemplateName91ec17a5f679e9da865a567912e67e5880465055 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName91ec17a5f679e9da865a567912e67e5880465055;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>