<?php
/**
* WoltLab Community Framework
* Template: imageViewer
* Compiled at: Wed, 28 May 2014 19:46:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'imageViewer';
?>
<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/ImageViewer.class.js"></script>
<script type="text/javascript">
	//<![CDATA[			
	// when the window is fully loaded, add image viewer
	Event.observe(window, 'load', function() {
		new ImageViewer($$('.enlargable'), {
			langCaption		: 'this.links.length > 1 ? "Bild " + (this.currentIndex + 1) + " von " + this.links.length + (this.currentLink.title ? (" - " + this.currentLink.title) : "") : (this.currentLink.title ? this.currentLink.title : "")',
			langPrevious		: 'Vorheriges Bild',
			langNext		: 'Nächstes Bild',
			langPlay		: 'Diashow starten (Bildwechsel alle 5 Sekunden)',
			langPause		: 'Diashow stoppen',
			langEnlarge		: 'Nur dieses Bild anzeigen (beendet die Bildbetrachtung)',
			langClose		: 'Schließen',
			imgBlankSrc		: '<?php echo RELATIVE_WCF_DIR; ?>images/imageViewer/blank.png',
			imgMenuSrc		: '<?php echo RELATIVE_WCF_DIR; ?>images/imageViewer/menu.png',
			imgPlaySrc		: '<?php ob_start(); ?>imageViewer/playM.png<?php $_icon48eaf8a95e6420bca83c59332c9f46c4b3bc8952 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon48eaf8a95e6420bca83c59332c9f46c4b3bc8952); ?>',
			imgPreviousSrc		: '<?php ob_start(); ?>imageViewer/previousM.png<?php $_icon1a762813c39629e8ee2d6b0107d83f485206d378 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon1a762813c39629e8ee2d6b0107d83f485206d378); ?>',
			imgNextSrc		: '<?php ob_start(); ?>imageViewer/nextM.png<?php $_icond9a8489186237eafe1e776bf5eea7c4eedb6b87a = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icond9a8489186237eafe1e776bf5eea7c4eedb6b87a); ?>',
			imgEnlargeSrc		: '<?php ob_start(); ?>imageViewer/enlargeM.png<?php $_icon0cb4a6e1b6f820e7bc178c7b7a2f37fef9e50754 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon0cb4a6e1b6f820e7bc178c7b7a2f37fef9e50754); ?>',
			imgPauseSrc		: '<?php ob_start(); ?>imageViewer/pauseM.png<?php $_iconc3f38cec4f9e21a99817b51e2a93e7c34491f502 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconc3f38cec4f9e21a99817b51e2a93e7c34491f502); ?>',
			imgCloseSrc		: '<?php ob_start(); ?>imageViewer/closeM.png<?php $_icond498c869496a4b33639bdac5b95c9605ad8d3cd2 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icond498c869496a4b33639bdac5b95c9605ad8d3cd2); ?>',
			imgPlayHoverSrc		: '<?php ob_start(); ?>imageViewer/playHoverM.png<?php $_iconf347349dd0843696c0b90275ebd5c9eda87ef622 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconf347349dd0843696c0b90275ebd5c9eda87ef622); ?>',
			imgPreviousHoverSrc	: '<?php ob_start(); ?>imageViewer/previousHoverM.png<?php $_icon5bf4c3fb3f349bce22baa128dcd48f3bc7d0d38e = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon5bf4c3fb3f349bce22baa128dcd48f3bc7d0d38e); ?>',
			imgNextHoverSrc		: '<?php ob_start(); ?>imageViewer/nextHoverM.png<?php $_icon896dd0b11f87ee18303d775cb7923c4306aff31e = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon896dd0b11f87ee18303d775cb7923c4306aff31e); ?>',
			imgEnlargeHoverSrc	: '<?php ob_start(); ?>imageViewer/enlargeHoverM.png<?php $_icon3f2737f5ca883d1112d2c9a2ba6477c3bbe26a85 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon3f2737f5ca883d1112d2c9a2ba6477c3bbe26a85); ?>',
			imgPauseHoverSrc	: '<?php ob_start(); ?>imageViewer/pauseHoverM.png<?php $_icon73e80da9841692838cf86dd2c9d9d8fc10490542 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon73e80da9841692838cf86dd2c9d9d8fc10490542); ?>',
			imgCloseHoverSrc	: '<?php ob_start(); ?>imageViewer/closeHoverM.png<?php $_icon95231021eb39c0f0432473debe7c6d1e29490ef0 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon95231021eb39c0f0432473debe7c6d1e29490ef0); ?>'	
		});
	});
//]]>
</script>