<?php
/**
* WoltLab Community Framework
* Template: headerMenu
* Compiled at: Wed, 28 May 2014 19:04:12 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'headerMenu';
?>

	<div id="mainMenu" class="mainMenu">
		<div class="mainMenuInner"><?php $this->assign('menuItemCounter', 0); ?><?php $this->assign('menuItemCount', count($this->v['this']->getPageMenu()->getMenuItems())); ?><ul><?php
if (count($this->v['this']->getPageMenu()->getMenuItems()) > 0) {
foreach ($this->v['this']->getPageMenu()->getMenuItems() as $this->v['item']) {
?><?php $this->assign('menuItemCounter', $this->v['menuItemCounter']+1); ?><li id="mainMenuItem<?php echo $this->v['item']['menuItemID']; ?>"<?php if ($this->v['item']['activeMenuItem'] || $this->v['menuItemCounter'] == 1 || $this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?> class="<?php if ($this->v['menuItemCounter'] == 1) { ?>first<?php } elseif ($this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?>last<?php } ?><?php if ($this->v['item']['activeMenuItem']) { ?><?php if ($this->v['menuItemCounter'] == 1 || $this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?>Active<?php } else { ?>active<?php } ?><?php } ?>"<?php } ?>><a href="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemLink']); ?>" title="<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_lang46d7de11c60d87d7b17c3f78a1a8de91375badd3 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang46d7de11c60d87d7b17c3f78a1a8de91375badd3, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>"><?php if ($this->v['item']['menuItemIconM']) { ?><img src="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemIconM']); ?>" alt="" /> <?php } ?><span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_langd9ef16654c4914f56c697708ebd21368ed271b19 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langd9ef16654c4914f56c697708ebd21368ed271b19, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a></li><?php } } ?></ul>
		</div>
	</div>