<?php
/**
* WoltLab Community Framework
* Template: footerMenu
* Compiled at: Wed, 28 May 2014 19:04:12 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'footerMenu';
?>
<?php if (count($this->v['this']->getPageMenu()->getMenuItems('footer')) > 0) { ?>
	<div id="footerMenu" class="footerMenu">
		<div class="footerMenuInner"><?php $this->assign('menuItemCounter', 0); ?><?php $this->assign('menuItemCount', count($this->v['this']->getPageMenu()->getMenuItems('footer'))); ?><ul><?php
if (count($this->v['this']->getPageMenu()->getMenuItems('footer')) > 0) {
foreach ($this->v['this']->getPageMenu()->getMenuItems('footer') as $this->v['item']) {
?><?php $this->assign('menuItemCounter', $this->v['menuItemCounter']+1); ?><li id="mainMenuItem<?php echo $this->v['item']['menuItemID']; ?>"<?php if ($this->v['item']['activeMenuItem'] || $this->v['menuItemCounter'] == 1 || $this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?> class="<?php if ($this->v['menuItemCounter'] == 1) { ?>first<?php } elseif ($this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?>last<?php } ?><?php if ($this->v['item']['activeMenuItem']) { ?><?php if ($this->v['menuItemCounter'] == 1 || $this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?>Active<?php } else { ?>active<?php } ?><?php } ?>"<?php } ?>><a href="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemLink']); ?>" title="<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_lang6d6fe6f35c3668e31c5c34ca4bc4ad3a2bfa807c = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang6d6fe6f35c3668e31c5c34ca4bc4ad3a2bfa807c, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>"><?php if ($this->v['item']['menuItemIconS']) { ?><img src="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemIconS']); ?>" alt="" /> <?php } ?><span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_langd7c8597e17284793a2090a580a696fdd0b747bc0 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langd7c8597e17284793a2090a580a696fdd0b747bc0, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a></li><?php } } ?></ul>
		</div>
	</div>
<?php } ?>