<?php
/**
* WoltLab Community Framework
* Template: redirect
* Compiled at: Wed, 28 May 2014 19:41:18 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'redirect';
?>
<?php
$outerTemplateName733f95ef270af0d7f39acfc890a6a3831008d847 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName733f95ef270af0d7f39acfc890a6a3831008d847;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Weiterleitung - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langd66c3120d3d13056b5bc0a614b87b116b680385a = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langd66c3120d3d13056b5bc0a614b87b116b680385a, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateNameb66f8f07e569a621f229880f7b6def779a388aa0 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameb66f8f07e569a621f229880f7b6def779a388aa0;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<meta http-equiv="refresh" content="<?php if (isset($this->v['wait'])) { ?><?php echo $this->v['wait']; ?><?php } else { ?>10<?php } ?>;URL=<?php echo StringUtil::encodeHTML($this->v['url']); ?>" />
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateName26ecea8f6ea28fb9f312a12df3786033399b2213 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName26ecea8f6ea28fb9f312a12df3786033399b2213;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<div class="success">
		<p><?php echo $this->v['message']; ?></p>
		<p><a href="<?php echo StringUtil::encodeHTML($this->v['url']); ?>">Falls die automatische Weiterleitung nicht funktioniert, klicken Sie bitte hier!</a></p>
	</div>

</div>

<?php
$outerTemplateNamedad39304b35f787fc0c03d7c8642f2e9d0c823f4 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamedad39304b35f787fc0c03d7c8642f2e9d0c823f4;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>