<?php
/**
* WoltLab Community Framework
* Template: userException
* Compiled at: Mon, 09 Jun 2014 19:02:57 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userException';
?>
<?php
$outerTemplateName4e4dd95c5547cb8959c0568bd130548d4928bbd9 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName4e4dd95c5547cb8959c0568bd130548d4928bbd9;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Fehlermeldung - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang202141e4fa777ee05f36efdffd2f0d78145cad65 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang202141e4fa777ee05f36efdffd2f0d78145cad65, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName2fe63288f6b708b24adeddcefaac4d77afd2f94f = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName2fe63288f6b708b24adeddcefaac4d77afd2f94f;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<script type="text/javascript">
		//<![CDATA[
		if (document.referrer) {
			onloadEvents.push(function() { document.getElementById('errorMessage').innerHTML += "<br /><a href=\"" + document.referrer + "\">Zurück zur vorherigen Seite</a>"; });
		}
		//]]>
	</script>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateName5dd1130c7910257fa9ed00e078aaa00e6bca54c0 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName5dd1130c7910257fa9ed00e078aaa00e6bca54c0;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	<p class="error" id="errorMessage">
		<?php echo $this->v['message']; ?>
	</p>
</div>

<!-- 
<?php echo StringUtil::encodeHTML($this->v['name']); ?> thrown in <?php echo StringUtil::encodeHTML($this->v['file']); ?> (<?php echo $this->v['line']; ?>)
Stracktrace:
<?php echo StringUtil::encodeHTML($this->v['stacktrace']); ?>
-->

<?php
$outerTemplateName2d9ff6421bda21eb8000ae6669b7e788cd5cc636 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName2d9ff6421bda21eb8000ae6669b7e788cd5cc636;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>