<?php
/**
* WoltLab Community Framework
* Template: userSearchUserListOptions
* Compiled at: Wed, 28 May 2014 19:44:07 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userSearchUserListOptions';
?>
<li<?php if ($this->v['action'] == 'notActivated') { ?> class="activeSubTabMenu"<?php } ?>><a href="index.php?page=UserList&amp;action=notActivated&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>"><span>Nicht aktivierte Benutzer</span></a></li>
<li<?php if ($this->v['action'] == 'new') { ?> class="activeSubTabMenu"<?php } ?>><a href="index.php?page=UserList&amp;action=new&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>"><span>Neue Benutzer</span></a></li>
<li<?php if ($this->v['action'] == 'banned') { ?> class="activeSubTabMenu"<?php } ?>><a href="index.php?page=UserList&amp;action=banned&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>"><span>Gesperrte Benutzer</span></a></li>