<?php
/**
* WoltLab Community Framework
* Template: setupWindowFooter
* Compiled at: Wed, 28 May 2014 19:04:07 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'setupWindowFooter';
?>
</div>
</body>
</html>