<?php
/**
* WoltLab Community Framework
* Template: setupFooter
* Compiled at: Wed, 28 May 2014 19:41:22 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'setupFooter';
?>
</div>
</body>
</html>