<?php
/**
* WoltLab Community Framework
* Template: packageInstallationFinish
* Compiled at: Wed, 28 May 2014 19:04:07 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'packageInstallationFinish';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><?php
$outerTemplateName92691789da63421bf8dd6ce7c15359d2642c011d = $this->v['tpl']['template'];
$this->includeTemplate('setupWindowHeader', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName92691789da63421bf8dd6ce7c15359d2642c011d;
$this->v['tpl']['includedTemplates']['setupWindowHeader'] = 1;
?>

<div class="nextButton">
	<input type="button" value="Weiter &raquo;" onclick="parent.location.href='<?php if ($this->v['installationType'] == 'setup') { ?>index.php?<?php } elseif ($this->v['installationType'] == 'install') { ?>index.php?form=PackageStartInstall&amp;action=install<?php } else { ?>index.php?page=PackageList<?php } ?>&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>'; parent.stopAnimating();" />
</div>

<script type="text/javascript">
	//<![CDATA[
	window.onload = function() {
	changeHeight();	
};
	<?php if (isset($this->v['progress'])) { ?>parent.setProgress(<?php echo $this->v['progress']; ?>);<?php } ?>
	parent.enableRollback(false);
	parent.showWindow(true);
	parent.setCurrentStep('Paket <b><?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['packageName']), $this)); ?></b>: <?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.acp.package.step.<?php if ($this->v['action'] == 'rollback') { ?>uninstall<?php } else { ?><?php echo $this->v['action']; ?><?php } ?>.<?php echo $this->v['step']; ?><?php $_lang486ef3bc8a27375ee10a68f715ed0c0a3ac69d92 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang486ef3bc8a27375ee10a68f715ed0c0a3ac69d92, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>');
	//]]>
</script>

<?php
$outerTemplateName97593fae04f4e2088860e704cc7ee4a2f8eb4f43 = $this->v['tpl']['template'];
$this->includeTemplate('setupWindowFooter', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName97593fae04f4e2088860e704cc7ee4a2f8eb4f43;
$this->v['tpl']['includedTemplates']['setupWindowFooter'] = 1;
?>