<?php
/**
* WoltLab Community Framework
* Template: setupWindowHeader
* Compiled at: Wed, 28 May 2014 19:04:07 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'setupWindowHeader';
?>
<?php echo '<?'; ?>
xml version="1.0" encoding="<?php echo CHARSET; ?>"<?php echo '?>'; ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" xml:lang="<?php echo LANGUAGE_CODE; ?>">
	<head>
		<title></title>
		<meta http-equiv="Content-Type" content="text/html; charset=<?php echo CHARSET; ?>" />
		<link href="<?php echo RELATIVE_WCF_DIR; ?>acp/style/extra/setupWindowStyle<?php if (PAGE_DIRECTION == 'rtl') { ?>-rtl<?php } ?>.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript">
			//<![CDATA[
			function changeHeight() {
				if (parent.document.getElementById('iframe').style.visibility != 'hidden') {
					parent.document.getElementById('iframe').style.height = document.getElementById('content').offsetHeight + 4 + 'px';
				}
			}
			//]]>
		</script>
	</head>
<body>
<div id="content" class="page" style="padding: 2px 4px">