<?php
/**
* WoltLab Community Framework
* Template: userListPMOption
* Compiled at: Wed, 28 May 2014 19:44:06 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userListPMOption';
?>
<?php if ($this->v['this']->user->getPermission('admin.user.canPMUser')) { ?>
	// send pm
	count = additionalOptions.length;
	additionalOptions[count] = new Object();
	additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?form=UserPM&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
	additionalOptions[count]['text'] = 'Private Nachricht senden';
	additionalOptions[count]['className'] = 'bottomSeparator';
<?php } ?>