<?php
/**
* WoltLab Community Framework
* Template: styleExport
* Compiled at: Mon, 09 Jun 2014 01:06:32 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'styleExport';
?>
<?php
$outerTemplateName7d28beec24524e5634a8e63ef90bc1c5bd2e75d4 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7d28beec24524e5634a8e63ef90bc1c5bd2e75d4;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div class="mainHeadline">
	<img src="<?php echo RELATIVE_WCF_DIR; ?>icon/styleExportL.png" alt="" />
	<div class="headlineContainer">
		<h2>Exportieren</h2>
		<p><?php echo StringUtil::encodeHTML($this->v['style']->styleName); ?></p>
	</div>
</div>

<?php if ($this->v['errorField']) { ?>
	<p class="error">Ihre Angaben sind ungültig. Bitte überprüfen Sie die markierten Eingabefelder.</p>
<?php } ?>

<div class="contentHeader">
	<div class="largeButtons">
		<ul><li><a href="index.php?page=StyleList&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>" title="Stile auflisten"><img src="<?php echo RELATIVE_WCF_DIR; ?>icon/styleM.png" alt="" /> <span>Stile auflisten</span></a></li></ul>
	</div>
</div>
<form method="post" action="index.php?form=StyleExport">
	<div class="border content">
		<div class="container-1">
			<fieldset>
				<legend>Dateien</legend>
				
				<?php if ($this->v['canExportTemplates']) { ?>
					<div class="formElement">
						<label><input type="checkbox" name="exportTemplates" value="1" <?php if ($this->v['exportTemplates'] == 1) { ?>checked="checked" <?php } ?>/> Templates exportieren (<?php echo StringUtil::encodeHTML($this->v['templatePackName']); ?>)</label>
					</div>
				<?php } ?>
				<div class="formElement">
					<label><input type="checkbox" name="exportImages" value="1" <?php if ($this->v['exportImages'] == 1) { ?>checked="checked" <?php } ?>/> Grafiken exportieren (<?php echo StringUtil::encodeHTML($this->v['imagesLocation']); ?>)</label>
				</div>
				<?php if ($this->v['canExportIcons']) { ?>
					<div class="formElement">
						<label><input type="checkbox" name="exportIcons" value="1" <?php if ($this->v['exportIcons'] == 1) { ?>checked="checked" <?php } ?>/> Icons exportieren (<?php echo StringUtil::encodeHTML($this->v['iconsLocation']); ?>)</label>
					</div>
				<?php } ?>
			</fieldset>
			
			<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
		</div>
	</div>
	
	<div class="formSubmit">
		<input type="submit" accesskey="s" value="Absenden" />
		<input type="reset" accesskey="r" value="Zurücksetzen" />
		<input type="hidden" name="packageID" value="<?php echo PACKAGE_ID; ?>" />
 		<?php echo SID_INPUT_TAG; ?>
 		<input type="hidden" name="styleID" value="<?php echo $this->v['styleID']; ?>" />
 	</div>
</form>

<?php
$outerTemplateName1eec56df927de228a14440bd8ed017a684ef6e86 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName1eec56df927de228a14440bd8ed017a684ef6e86;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>