<?php
/**
* WoltLab Community Framework
* Template: styleImport
* Compiled at: Wed, 28 May 2014 19:44:22 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'styleImport';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
?><?php
$outerTemplateName47820a4c427ad810a9773e479851f705543dc8e1 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName47820a4c427ad810a9773e479851f705543dc8e1;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div class="mainHeadline">
	<img src="<?php echo RELATIVE_WCF_DIR; ?>icon/styleImportL.png" alt="" />
	<div class="headlineContainer">
		<h2>Stil importieren</h2>
		<p>Eine beliebte Quelle für kostenlose Stile und andere Erweiterungen ist der <span class="externalURL"><a href="http://www.woltlab.com/pluginstore/" title="Den WoltLab Plug-in Store aufrufen">WoltLab Plugin-Store</a></span>. Als WoltLab-Kunde sind Sie im Pluginstore bereits registriert.</p>
	</div>
</div>

<?php if ($this->v['errorField']) { ?>
	<p class="error">Ihre Angaben sind ungültig. Bitte überprüfen Sie die markierten Eingabefelder.</p>
<?php } ?>

<?php if (isset($this->v['success'])) { ?>
	<p class="success">Der Stil &raquo;<?php echo StringUtil::encodeHTML($this->v['style']->styleName); ?>&laquo; wurde erfolgreich importiert.</p>	
<?php } ?>

<div class="contentHeader">
	<div class="largeButtons">
		<ul><li><a href="index.php?page=StyleList&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>" title="Stile auflisten"><img src="<?php echo RELATIVE_WCF_DIR; ?>icon/styleM.png" alt="" /> <span>Stile auflisten</span></a></li></ul>
	</div>
</div>
<form enctype="multipart/form-data" method="post" action="index.php?form=StyleImport">
	<div class="border content">
		<div class="container-1">
			<fieldset>
				<legend>Quelle</legend>
				
				<div class="formElement<?php if ($this->v['errorField'] == 'styleUpload') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="styleUpload">Stil-Datei hochladen</label>
					</div>
					<div class="formField">
						<input type="file" name="styleUpload" id="styleUpload" />
						<?php if ($this->v['errorField'] == 'styleUpload') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
								<?php if ($this->v['errorType'] == 'invalid') { ?>Der Stil konnte nicht importiert werden. Es handelt sich nicht um eine gültige Stil-Datei.<?php } ?>
								<?php if ($this->v['errorType'] == 'uploadFailed') { ?>Beim Hochladen des Stils ist ein Fehler aufgetreten.<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
				
				<div class="formElement<?php if ($this->v['errorField'] == 'styleURL') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="styleURL">Stil-Datei herunterladen</label>
					</div>
					<div class="formField">
						<input type="text" class="inputText" name="styleURL" id="styleURL" value="<?php echo StringUtil::encodeHTML($this->v['styleURL']); ?>" />
						<?php if ($this->v['errorField'] == 'styleURL') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'invalid') { ?>Der Stil konnte nicht importiert werden. Es handelt sich nicht um eine gültige Stil-Datei.<?php } ?>
								<?php if ($this->v['errorType'] == 'downloadFailed') { ?>Beim Herunterladen des Stils ist ein Fehler aufgetreten.<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
			</fieldset>
			
			<?php if (count($this->v['availableStyles']) > 0) { ?>
				<fieldset>
					<legend>Ziel</legend>
					
					<div class="formElement<?php if ($this->v['errorField'] == 'destinationStyleID') { ?> formError<?php } ?>" id="destinationStyleIDDiv">
						<div class="formFieldLabel">
							<label for="destinationStyleID">Stil</label>
						</div>
						<div class="formField">
							<select name="destinationStyleID" id="destinationStyleID">
								<option></option>
								<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['availableStyles'], 'selected' => $this->v['destinationStyleID']), $this); ?>
							</select>
							<?php if ($this->v['errorField'] == 'destinationStyleID') { ?>
								<p class="innerError">
									<?php if ($this->v['errorType'] == 'empty') { ?>Bitte füllen Sie dieses Eingabefeld aus.<?php } ?>
								</p>
							<?php } ?>
						</div>
						<div class="formFieldDesc hidden" id="destinationStyleIDHelpMessage">
							Optional können Sie hier einen vorhandenen Stil auswählen, der mit der angegebenen Stil-Datei aktualisiert werden soll.
						</div>
					</div>
					<script type="text/javascript">//<![CDATA[
						inlineHelp.register('destinationStyleID');
					//]]></script>
				</fieldset>
			<?php } ?>
			
			<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
		</div>
	</div>
	
	<div class="formSubmit">
		<input type="submit" accesskey="s" value="Absenden" />
		<input type="reset" accesskey="r" value="Zurücksetzen" />
		<input type="hidden" name="packageID" value="<?php echo PACKAGE_ID; ?>" />
 		<?php echo SID_INPUT_TAG; ?>
 	</div>
</form>

<?php
$outerTemplateNamefb5b37e17a7fd142a9052d52800019c5f3b5d12c = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamefb5b37e17a7fd142a9052d52800019c5f3b5d12c;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>