<?php
/**
* WoltLab Community Framework
* Template: userListUserMergeOption
* Compiled at: Wed, 28 May 2014 19:44:07 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userListUserMergeOption';
?>
// merge users
count = additionalOptions.length;
additionalOptions[count] = new Object();
additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?form=UserMerge&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
additionalOptions[count]['text'] = 'Zusammenführen';
additionalOptions[count]['className'] = 'bottomSeparator';